import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {Service} from '../automation/service.mjs';

test('ChatGPT Assisted import and repair cannot approve without motion observations',async t=>{
  const root=await mkdtemp(path.join(tmpdir(),'sprited-assisted-'));t.after(()=>rm(root,{recursive:true,force:true}));
  const service=await new Service(root).init();t.after(()=>service.close());
  const images=await service.page.evaluate(()=>[40,70,100,130,160,130,100,70,129].map(value=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const context=canvas.getContext('2d');context.fillStyle=`rgb(${value} ${value} ${value})`;context.fillRect(18,8,28,48);return canvas.toDataURL('image/png').split(',')[1];}));
  await writeFile(path.join(root,'reference.png'),Buffer.from(images[0],'base64'));
  const character=(await service.call('character/create',{path:'reference.png',name:'Assisted Guardian'})).result;
  const created=await service.call('agent/generate-animation',{character_id:character.id,animation_type:'WALKING',frames:8,provider:'chatgpt_assisted'});assert.equal(created.status,'user_action_required');const id=created.result.attempt_id;
  const prepared=(await service.call('agent/prepare-assisted-request',{animation_id:id,frame_index:0})).result;assert.deepEqual(prepared.missing_frame_indexes,[0,1,2,3,4,5,6,7]);assert.equal(prepared.frame_plan.length,8);assert.match(prepared.prompt,/frame 1 of an 8-frame walking animation/i);
  for(let frame_index=0;frame_index<8;frame_index++)await service.call('agent/submit-frame',{animation_id:id,frame_index,provider:'chatgpt_assisted',format:'png',image_base64:images[frame_index]});
  let frames=(await service.call('agent/list-frames',{animation_id:id})).result;assert.deepEqual(frames.map(frame=>frame.frame_index),[0,1,2,3,4,5,6,7]);assert.deepEqual((await service.call('agent/prepare-assisted-request',{animation_id:id,frame_index:7})).result.missing_frame_indexes,[]);const stable=frames.map(frame=>frame.frame_id);
  const preview1=(await service.call('agent/build-gif',{animation_id:id})).result;assert.equal((await service.readContentReference(preview1.asset_reference)).mime_type,'image/gif');const validation=(await service.call('agent/validate-animation',{animation_id:id})).result;assert.equal(validation.frame_count,8);assert.ok(Array.isArray((await service.call('agent/detect-bad-frames',{animation_id:id})).result.bad_frames));
  await service.call('agent/semantic-validate-animation',{animation_id:id,supervisor_result:{passed:false,score:60,issues:[{type:'leg_progression',frame_index:5,severity:'high',description:'The gait needs a corrected leg transition.'}],bad_frames:[5]}});const plan=(await service.call('agent/get-repair-plan',{animation_id:id})).result,repair=(await service.call('agent/prepare-assisted-request',{animation_id:id,frame_index:5,repair_plan_id:plan.repair_plan_id})).result;assert.equal(repair.request_kind,'repair');assert.equal(repair.asset_references.current,`frame:${stable[5]}`);assert.equal(repair.asset_references.previous,`frame:${stable[4]}`);assert.equal(repair.asset_references.next,`frame:${stable[6]}`);
  await service.call('agent/submit-repair-frame',{repair_plan_id:plan.repair_plan_id,frame_index:5,provider:'chatgpt_assisted',format:'png',image_base64:images[8]});const evaluated=(await service.call('agent/evaluate-repair',{repair_plan_id:plan.repair_plan_id})).result;assert.ok(evaluated.gif_preview_id);await service.call('agent/semantic-validate-animation',{animation_id:id,supervisor_result:{passed:true,score:95,issues:[],bad_frames:[]}});frames=(await service.call('agent/list-frames',{animation_id:id})).result;assert.deepEqual(frames.map(frame=>frame.frame_id),stable);
  const approved=await service.call('agent/use-result',{id});assert.equal(approved.success,false);assert.match(approved.errors[0],/temporal validation/i);const blocked=await service.core('workflow/animation/status',{id});assert.equal(blocked.user_approved,false);assert.equal(blocked.temporal_inspection.status,'INSUFFICIENT_MOTION_OBSERVATION');
  const changes=(await service.call('agent/get-recent-changes',{animation_type:'WALKING'})).result;assert.ok(changes.recent.some(event=>event.event_type==='frame_imported'));assert.ok(!changes.recent.some(event=>event.event_type==='animation_approved'));assert.equal(JSON.stringify(changes).includes(root),false);await stat(path.join(root,'activity','activity-log.jsonl'));await stat(path.join(root,'experience','experience-history.json'));
});
