import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {chatgptTools,ChatGptAppAdapter} from '../automation/chatgpt-app.mjs';import {createMcpSession} from '../automation/mcp.mjs';import {Service} from '../automation/service.mjs';

test('ChatGPT App exposes only the eleven high-level tools',async()=>{const calls=[],service={pluginConnect:async()=>{},pluginHeartbeat:async()=>{},pluginDisconnect:async()=>{},call:async(action,args)=>{calls.push([action,args]);return {success:true,result:{quality_state:'GOOD_ENOUGH'},warnings:[],errors:[],output_paths:[]};}},session=createMcpSession(service,{plugin:true,sessionId:'remote-test'});await session.handle({jsonrpc:'2.0',id:1,method:'initialize',params:{clientInfo:{name:'ChatGPT'}}});const listed=await session.handle({jsonrpc:'2.0',id:2,method:'tools/list',params:{}});assert.deepEqual(listed.result.tools.map(tool=>tool.name),['prepare_animation_prompt','analyze_spritesheet','build_preview','validate_animation','get_bad_frames','prepare_repair_prompt','evaluate_quality','get_learning_summary','get_recent_changes','export_spritesheet','export_gif']);assert.equal(JSON.stringify(listed).includes('path'),false);await session.close();});

test('prompt, quality, learning and changes reuse existing service actions',async()=>{const calls=[],service={call:async(action,args)=>{calls.push(action);if(action==='agent/generate-animation')return {success:true,result:{id:'run-1'}};if(action==='agent/prepare-assisted-request')return {success:true,result:{prompt:'walk'},output_paths:[]};return {success:true,result:{quality_state:'GOOD_ENOUGH'},output_paths:[]};}},adapter=new ChatGptAppAdapter(service);assert.equal((await adapter.call('prepare_animation_prompt',{character_id:'character-1',animation_type:'WALKING'})).result.prompt,'walk');await adapter.call('evaluate_quality',{animation_id:'run-1'});await adapter.call('get_learning_summary',{});await adapter.call('get_recent_changes',{});assert.deepEqual(calls,['agent/generate-animation','agent/prepare-assisted-request','agent/get-animation-status','agent/get-experience-summary','agent/get-recent-changes']);});

test('image schemas reject arbitrary filesystem paths',()=>{for(const tool of chatgptTools)assert.equal(Object.hasOwn(tool.inputSchema.properties,'path'),false);assert.equal(chatgptTools.length,11);});

test('remote adapter slices a one-shot SpriteSheet and builds a GIF with the shared engine',async t=>{const root=await mkdtemp(path.join(tmpdir(),'sprited-chatgpt-'));t.after(()=>rm(root,{recursive:true,force:true}));const service=await new Service(root).init();t.after(()=>service.close());const sheet=await service.page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const context=canvas.getContext('2d');for(let index=0;index<4;index++){context.fillStyle=`rgb(${50+index*40} ${80+index*20} ${120+index*15})`;context.fillRect(index%2*64+16,Math.floor(index/2)*64+8,32,48);}return canvas.toDataURL('image/png').split(',')[1];}),reference=await service.page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=64;canvas.getContext('2d').fillRect(16,8,32,48);return canvas.toDataURL('image/png').split(',')[1];}),adapter=new ChatGptAppAdapter(service),prepared=await adapter.call('prepare_animation_prompt',{character_name:'Remote Guardian',reference_image_base64:reference,reference_format:'png',animation_type:'IDLE',frame_count:4,quality_mode:'fast',prompt_mode:'spritesheet'});assert.equal(prepared.success,true,JSON.stringify(prepared));const animationId=prepared.result.animation_id,analyzed=await adapter.call('analyze_spritesheet',{animation_id:animationId,image_base64:sheet,image_format:'png',columns:2,rows:2,quality_mode:'fast'});assert.equal(analyzed.result.frame_count,4);assert.deepEqual(analyzed.result.frame_size,[64,64]);assert.ok(analyzed.asset_reference.startsWith('preview:'));assert.equal((await service.readContentReference(analyzed.asset_reference)).mime_type,'image/gif');});
