import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,stat,writeFile} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {clientConfigPath,configureMcpClient} from '../automation/client-config.mjs';

const exists=file=>stat(file).then(()=>true,()=>false);
const fixture=async()=>{const home=await mkdtemp(path.join(os.tmpdir(),'sprited-client-config-'));await mkdir(path.join(home,'.cline','data','settings'),{recursive:true});await mkdir(path.join(home,'.codex'),{recursive:true});return home;};
const request=(client,home,token='current-secret-token')=>({client,home,command:'C:\\SPRITED\\runtime\\node.exe',cliPath:'C:\\SPRITED\\automation\\cli.mjs',apiUrl:'http://127.0.0.1:47821',token});

test('detects known Cline and Codex user config paths',async()=>{const home=await fixture();assert.equal(clientConfigPath('cline',home),path.join(home,'.cline','data','settings','cline_mcp_settings.json'));assert.equal(clientConfigPath('codex',home),path.join(home,'.codex','config.toml'));});

test('Cline insert preserves every unrelated server and creates an exact backup',async()=>{const home=await fixture(),file=clientConfigPath('cline',home),original={mcpServers:{'godot-ai':{command:'godot',args:['mcp'],autoApprove:['scene']},other:{command:'other',disabled:true}},theme:'dark'};await writeFile(file,JSON.stringify(original,null,2));const result=await configureMcpClient(request('cline',home)),saved=JSON.parse(await readFile(file,'utf8'));assert.deepEqual(saved.mcpServers['godot-ai'],original.mcpServers['godot-ai']);assert.deepEqual(saved.mcpServers.other,original.mcpServers.other);assert.equal(saved.theme,'dark');assert.equal(saved.mcpServers.sprited.disabled,false);assert.deepEqual(saved.mcpServers.sprited.args,['C:\\SPRITED\\automation\\cli.mjs','mcp','--api','http://127.0.0.1:47821']);assert.equal(saved.mcpServers.sprited.env.SPRITED_TOKEN,'current-secret-token');assert.deepEqual(JSON.parse(await readFile(file+'.sprited-backup','utf8')),original);assert.equal(result.token_synchronized,true);assert.equal(JSON.stringify(result).includes('current-secret-token'),false);assert.match(result.message,/Restart or reconnect the client, then press Test Connection/);});

test('Cline update keeps existing sprited autoApprove and synchronizes only managed values',async()=>{const home=await fixture(),file=clientConfigPath('cline',home),godot={command:'godot-old',env:{GODOT:'yes'},autoApprove:['all']},old={mcpServers:{'godot-ai':godot,sprited:{command:'old',args:['old'],disabled:true,autoApprove:['list_characters'],env:{KEEP:'yes',SPRITED_TOKEN:'old'}}}};await writeFile(file,JSON.stringify(old));await configureMcpClient(request('cline',home,'new-token'));const saved=JSON.parse(await readFile(file,'utf8'));assert.deepEqual(saved.mcpServers['godot-ai'],godot);assert.deepEqual(saved.mcpServers.sprited.autoApprove,['list_characters']);assert.equal(saved.mcpServers.sprited.env.KEEP,'yes');assert.equal(saved.mcpServers.sprited.env.SPRITED_TOKEN,'new-token');assert.equal(saved.mcpServers.sprited.disabled,false);});

test('Codex insert and update preserve godot-ai, models, projects, plugins, and custom sprited values',async()=>{const home=await fixture(),file=clientConfigPath('codex',home),original=`model = "gpt-6"\n\n[mcp_servers.godot-ai]\ncommand = "godot"\nargs = ["mcp"]\n\n[projects.'C:\\\\Game']\ntrust_level = "trusted"\n\n[plugins.example]\nenabled = true\n`;await writeFile(file,original);let result=await configureMcpClient(request('codex',home)),saved=await readFile(file,'utf8');for(const exact of ['model = "gpt-6"','[mcp_servers.godot-ai]\ncommand = "godot"\nargs = ["mcp"]',"[projects.'C:\\\\Game']\ntrust_level = \"trusted\"",'[plugins.example]\nenabled = true'])assert.ok(saved.includes(exact));assert.match(saved,/\[mcp_servers\.sprited\][\s\S]*command = "C:\\\\SPRITED\\\\runtime\\\\node\.exe"/);assert.match(saved,/\[mcp_servers\.sprited\.env\]\nSPRITED_TOKEN = "current-secret-token"/);assert.equal(await readFile(file+'.sprited-backup','utf8'),original);assert.equal(JSON.stringify(result).includes('current-secret-token'),false);
  saved=saved.replace('args = ["C:\\\\SPRITED\\\\automation\\\\cli.mjs", "mcp", "--api", "http://127.0.0.1:47821"]','args = ["old"]\nstartup_timeout_sec = 30').replace('SPRITED_TOKEN = "current-secret-token"','SPRITED_TOKEN = "old"\nKEEP = "yes"');await writeFile(file,saved);await configureMcpClient(request('codex',home,'fresh'));const updated=await readFile(file,'utf8');assert.equal((updated.match(/\[mcp_servers\.sprited\]/g)||[]).length,1);assert.equal((updated.match(/\[mcp_servers\.sprited\.env\]/g)||[]).length,1);assert.ok(updated.includes('startup_timeout_sec = 30'));assert.ok(updated.includes('KEEP = "yes"'));assert.ok(updated.includes('SPRITED_TOKEN = "fresh"'));assert.ok(updated.includes('[mcp_servers.godot-ai]\ncommand = "godot"\nargs = ["mcp"]'));});

test('Codex accepts multiline arrays while still rejecting incomplete values',async()=>{const home=await fixture(),file=clientConfigPath('codex',home),original='model = "gpt-6"\nenabled_tools = [\n  "shell",\n  "browser",\n]\n\n[mcp_servers.godot-ai]\ncommand = "godot"\n';await writeFile(file,original);await configureMcpClient(request('codex',home));const saved=await readFile(file,'utf8');assert.ok(saved.includes('enabled_tools = [\n  "shell",\n  "browser",\n]'));assert.ok(saved.includes('[mcp_servers.godot-ai]\ncommand = "godot"'));});

test('Codex replaces a multiline existing sprited args value without retaining dangling lines',async()=>{const home=await fixture(),file=clientConfigPath('codex',home),original='[mcp_servers.sprited]\ncommand = "old"\nargs = [\n  "old-cli",\n  "mcp",\n]\nstartup_timeout_sec = 30\n\n[mcp_servers.other]\ncommand = "other"\n';await writeFile(file,original);await configureMcpClient(request('codex',home));const saved=await readFile(file,'utf8');assert.equal(saved.includes('"old-cli"'),false);assert.ok(saved.includes('startup_timeout_sec = 30'));assert.ok(saved.includes('[mcp_servers.other]\ncommand = "other"'));});

test('invalid JSON and TOML are not modified and do not receive backups',async()=>{for(const [client,bad] of [['cline','{"mcpServers":'],['codex','[mcp_servers.godot-ai\ncommand = "godot"']]){const home=await fixture(),file=clientConfigPath(client,home);await writeFile(file,bad);await assert.rejects(()=>configureMcpClient(request(client,home)),/invalid|incomplete/i);assert.equal(await readFile(file,'utf8'),bad);assert.equal(await exists(file+'.sprited-backup'),false);}});

test('switching repeatedly enables only selected SPRITED entry and preserves both client configs',async()=>{const home=await fixture(),clineFile=clientConfigPath('cline',home),codexFile=clientConfigPath('codex',home),clineGodot={command:'godot',autoApprove:['scene']},clineOther={command:'other',disabled:false};await writeFile(clineFile,JSON.stringify({theme:'dark',mcpServers:{'godot-ai':clineGodot,other:clineOther,sprited:{command:'old-cline',disabled:false,autoApprove:['list'],env:{SPRITED_TOKEN:'cline-old',KEEP:'yes'}}}},null,2));const codexGodot='[mcp_servers.godot-ai]\ncommand = "godot"\nargs = ["mcp"]',codexOther='[mcp_servers.node_repl]\ncommand = "node-repl"',codexOriginal=`model = "gpt-6"\n\n${codexGodot}\n\n${codexOther}\n\n[mcp_servers.sprited]\ncommand = "old-codex"\nenabled = true\n\n[mcp_servers.sprited.env]\nSPRITED_TOKEN = "codex-old"\nKEEP = "yes"\n`;await writeFile(codexFile,codexOriginal);
  let result=await configureMcpClient(request('codex',home,'codex-current')),cline=JSON.parse(await readFile(clineFile,'utf8')),codex=await readFile(codexFile,'utf8');assert.equal(result.active_client,'codex');assert.equal(cline.mcpServers.sprited.disabled,true);assert.equal(cline.mcpServers.sprited.env.SPRITED_TOKEN,'cline-old');assert.deepEqual(cline.mcpServers['godot-ai'],clineGodot);assert.deepEqual(cline.mcpServers.other,clineOther);assert.ok(codex.includes('enabled = true'));assert.ok(codex.includes('SPRITED_TOKEN = "codex-current"'));assert.ok(codex.includes(codexGodot));assert.ok(codex.includes(codexOther));assert.equal(await exists(clineFile+'.sprited-backup'),true);assert.equal(await exists(codexFile+'.sprited-backup'),true);
  result=await configureMcpClient(request('cline',home,'cline-current'));cline=JSON.parse(await readFile(clineFile,'utf8'));codex=await readFile(codexFile,'utf8');assert.equal(result.active_client,'cline');assert.equal(cline.mcpServers.sprited.disabled,false);assert.equal(cline.mcpServers.sprited.env.SPRITED_TOKEN,'cline-current');assert.deepEqual(cline.mcpServers.sprited.autoApprove,['list']);assert.ok(codex.includes('enabled = false'));assert.ok(codex.includes('SPRITED_TOKEN = "codex-current"'));assert.ok(codex.includes(codexGodot));assert.ok(codex.includes(codexOther));
  await configureMcpClient(request('codex',home,'codex-next'));cline=JSON.parse(await readFile(clineFile,'utf8'));codex=await readFile(codexFile,'utf8');assert.equal(cline.mcpServers.sprited.disabled,true);assert.equal(cline.mcpServers.sprited.env.SPRITED_TOKEN,'cline-current');assert.ok(codex.includes('enabled = true'));assert.ok(codex.includes('SPRITED_TOKEN = "codex-next"'));});

test('invalid inactive client config prevents partial selected-client mutation',async()=>{const home=await fixture(),clineFile=clientConfigPath('cline',home),codexFile=clientConfigPath('codex',home),valid='[mcp_servers.sprited]\ncommand = "old"\nenabled = true\n';await writeFile(codexFile,valid);await writeFile(clineFile,'{"mcpServers":');await assert.rejects(()=>configureMcpClient(request('codex',home)),/invalid JSON/);assert.equal(await readFile(codexFile,'utf8'),valid);assert.equal(await readFile(clineFile,'utf8'),'{"mcpServers":');});
