import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {LocalProcessProvider} from '../automation/image-provider.mjs';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XyVZ5wAAAABJRU5ErkJggg==','base64'),bridge=fileURLToPath(new URL('../automation/providers/sprited-comfy-bridge.mjs',import.meta.url)),generateWorkflow=fileURLToPath(new URL('./fixtures/comfy-generate-workflow.json',import.meta.url)),editWorkflow=fileURLToPath(new URL('./fixtures/comfy-edit-workflow.json',import.meta.url));
const body=request=>new Promise(resolve=>{const chunks=[];request.on('data',chunk=>chunks.push(chunk));request.on('end',()=>resolve(Buffer.concat(chunks)));});
async function fakeComfy(mode='success'){
  const state={uploads:0,prompts:[]},server=http.createServer(async(request,response)=>{const url=new URL(request.url,'http://local');if(url.pathname==='/system_stats')return response.end('{}');if(url.pathname==='/upload/image'){await body(request);state.uploads++;response.setHeader('content-type','application/json');return response.end(JSON.stringify({name:`asset-${state.uploads}.png`,subfolder:'input',type:'input'}));}if(url.pathname==='/prompt'){state.prompts.push(JSON.parse((await body(request)).toString()));response.setHeader('content-type','application/json');return response.end(JSON.stringify({prompt_id:'prompt-1'}));}if(url.pathname==='/history/prompt-1'){response.setHeader('content-type','application/json');if(mode==='timeout')return response.end('{}');if(mode==='execution-error')return response.end(JSON.stringify({'prompt-1':{status:{status_str:'error'},outputs:{}}}));if(mode==='no-output')return response.end(JSON.stringify({'prompt-1':{status:{status_str:'success'},outputs:{}}}));return response.end(JSON.stringify({'prompt-1':{status:{status_str:'success'},outputs:{'9':{images:[{filename:'result.png',subfolder:'',type:'output'}]}}}}));}if(url.pathname==='/view'){response.setHeader('content-type',mode==='invalid'?'text/plain':'image/png');return response.end(mode==='invalid'?Buffer.from('broken'):png);}response.statusCode=404;response.end();});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));return {state,server,endpoint:`http://127.0.0.1:${server.address().port}`,close:()=>new Promise(resolve=>server.close(resolve))};
}
async function setup(endpoint,{timeout=1500}={}){const root=await mkdtemp(path.join(os.tmpdir(),'sprited-comfy-')),config=path.join(root,'bridge.json');await writeFile(config,JSON.stringify({endpoint,generate_workflow:generateWorkflow,edit_workflow:editWorkflow,timeout_ms:timeout}));const provider=new LocalProcessProvider({enabled:true,executable:process.execPath,script:bridge,arguments:[config],timeout_ms:Math.min(60000,timeout+1500)},{tempRoot:path.join(root,'requests'),assetResolver:async()=>({bytes:png,mime_type:'image/png'})});return {root,provider};}
const context={animation_id:'walk-1',frame_index:5,animation_type:'WALKING',reference_asset:'character:guardian',current_frame:'frame:5',previous_frame:'frame:4',next_frame:'frame:6',repair_reasons:['leg_progression'],instruction:'Correct the leading leg.',assets:{reference:'character:guardian',current:'frame:5',previous:'frame:4',next:'frame:6'}};

test('Comfy bridge maps generate/edit requests and materialized references',async()=>{const fake=await fakeComfy(),value=await setup(fake.endpoint);try{const generated=await value.provider.generate_frame({...context,current_frame:null,previous_frame:null,next_frame:null,assets:{reference:context.assets.reference}});assert.equal(generated.provider,'local_process');assert.equal(fake.state.uploads,1);assert.match(fake.state.prompts[0].prompt['1'].inputs.image,/^input\/asset-1\.png$/);assert.match(fake.state.prompts[0].prompt['2'].inputs.text,/Frame index: 5/);fake.state.uploads=0;const edited=await value.provider.edit_frame(context);assert.equal(edited.format,'png');assert.equal(fake.state.uploads,4);const prompt=fake.state.prompts[1].prompt;assert.match(prompt['2'].inputs.image,/asset-2\.png$/);assert.match(prompt['3'].inputs.image,/asset-3\.png$/);assert.match(prompt['4'].inputs.image,/asset-4\.png$/);assert.match(prompt['5'].inputs.text,/leg_progression/);}finally{await rm(value.root,{recursive:true,force:true});await fake.close();}});
test('Comfy bridge returns clean unreachable and timeout errors',async()=>{let value=await setup('http://127.0.0.1:1');try{await assert.rejects(()=>value.provider.generate_frame(context),/ComfyUI is not reachable/);}finally{await rm(value.root,{recursive:true,force:true});}const fake=await fakeComfy('timeout');value=await setup(fake.endpoint,{timeout:200});try{await assert.rejects(()=>value.provider.generate_frame(context),/timed out/);}finally{await rm(value.root,{recursive:true,force:true});await fake.close();}});
test('Comfy bridge rejects execution failure, missing output and invalid output',async()=>{for(const mode of ['execution-error','no-output','invalid']){const fake=await fakeComfy(mode),value=await setup(fake.endpoint),pattern=mode==='execution-error'?/execution failed/:mode==='no-output'?/no output image/:/invalid output image/;try{await assert.rejects(()=>value.provider.generate_frame(context),pattern);}finally{await rm(value.root,{recursive:true,force:true});await fake.close();}}});
