import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {ExperienceService} from '../automation/experience-service.mjs';
import {ProgressTracker} from '../automation/progress-tracker.mjs';
import {createRepairPlan} from '../automation/repair-orchestrator.mjs';
import {Service} from '../automation/service.mjs';
import '../public/character-workflow.js';

async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'sprited-history-')),options={experiencePath:path.join(root,'experience.json'),timingPath:path.join(root,'timing.json')},service=await new ExperienceService(options).init();return {root,options,service};}
const experience=(repair_action,repair_succeeded,extra={})=>({animation_type:'WALKING',issue_type:'leg_progression',repair_action,repair_succeeded,provider:'local_process',technical_score_before:50,semantic_score_before:45,technical_score_after:repair_succeeded?80:40,semantic_score_after:repair_succeeded?75:35,...extra});

test('successful and failed repair experiences persist without trusting one success',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const good=await f.service.record_experience(experience('regenerate_with_neighbors',true)),bad=await f.service.record_experience(experience('current_frame_only',false));assert.equal(good.repair_succeeded,true);assert.equal(bad.repair_succeeded,false);const ranking=f.service.rank_repair_strategies({animation_type:'WALKING',issue_type:'leg_progression',provider:'local_process'},'regenerate_with_neighbors');assert.equal(ranking.strategy_source,'default');assert.equal(ranking.ranked_strategies.find(item=>item.repair_action==='regenerate_with_neighbors').confidence,'experimental');const reloaded=await new ExperienceService(f.options).init();assert.equal(reloaded.query_relevant_experience({animation_type:'WALKING',issue_type:'leg_progression'}).length,2);});

test('repair evaluation helper records improved and failed outcomes automatically',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const runner={experienceService:f.service},run={animation_type:'WALKING',image_provider_id:'local_process',character_reference:{}},plan={repair_plan_id:'plan-good',previous_validation_score:50,semantic_score:45,repaired_frame_indexes:[2],frames_to_repair:[{frame_index:2,reasons:['leg_progression'],repair_action:'regenerate_with_neighbors'}],repair_results:[{frame_index:2,provider:'local_process',repair_action:'regenerate_with_neighbors',instruction_summary:'keep neighboring gait context'}]};let records=await Service.prototype.recordRepairExperiences.call(runner,run,plan,{score:75});assert.equal(records[0].repair_succeeded,true);plan.repair_plan_id='plan-bad';records=await Service.prototype.recordRepairExperiences.call(runner,run,plan,{score:40});assert.equal(records[0].repair_succeeded,false);assert.equal(f.service.experiences.records.length,2);});

test('no-history strategy keeps the existing repair default',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const ranking=f.service.rank_repair_strategies({animation_type:'ATTACK',issue_type:'visual_jump'},'regenerate_with_neighbors');assert.equal(ranking.strategy_source,'default');assert.equal(ranking.repair_action,'regenerate_with_neighbors');});

test('repair plan exposes compact experience metadata without overriding evidence',()=>{const run={id:'run',animation_type:'WALKING',character_profile_id:'character',frame_records:[0,1,2].map(frame_index=>({frame_index,frame_id:`f${frame_index}`})),technical_validation:{score:55,issues:[]},semantic_validation:{semantic_score:40,issues:[{type:'leg_progression',frame_index:1,severity:'high'}]},repair_plans:[]},plan=createRepairPlan(run,{strategyByIssue:{leg_progression:{repair_action:'regenerate_with_neighbors',strategy_source:'experience',historical_attempts:7,historical_success_rate:.8}}}),target=plan.frames_to_repair[0];assert.equal(target.strategy_source,'experience');assert.equal(target.historical_attempts,7);assert.equal(target.historical_success_rate,.8);assert.deepEqual(target.reasons,['leg_progression']);});

test('provider timing persists and drives ETA',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));await f.service.record_timing('generate_frame','openai_api',1000);await f.service.record_timing('generate_frame','openai_api',2000);assert.equal(f.service.average_duration('generate_frame','openai_api'),1300);const tracker=new ProgressTracker(f.service,{now:()=>Date.parse('2026-01-01T00:00:10Z')}),progress=tracker.update(null,{animation_id:'a',stage:'generating',provider:'openai_api',remaining_operations:{generate_frame:2}});assert.equal(progress.estimated_remaining_ms,2600);const reloaded=await new ExperienceService(f.options).init();assert.equal(reloaded.average_duration('generate_frame','openai_api'),1300);});

test('progress advances, remains monotonic, and extends ETA for discovered repairs',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));await f.service.record_timing('repair_generation','local_process',5000);await f.service.record_timing('revalidating','any',1000);let now=Date.parse('2026-01-01T00:00:00Z'),tracker=new ProgressTracker(f.service,{now:()=>now}),progress=tracker.update(null,{animation_id:'a',stage:'validating',provider:'local_process',remaining_operations:{revalidating:1}});const firstEta=progress.estimated_remaining_ms,firstPercent=progress.progress_percent;now+=1200;progress=tracker.update(progress,{animation_id:'a',stage:'diagnosing',provider:'local_process',current_repair_attempt:1,remaining_operations:{repair_generation:2,revalidating:1}});assert.ok(progress.progress_percent>=firstPercent);assert.ok(progress.estimated_remaining_ms>firstEta);assert.equal(progress.current_stage,'diagnosing');assert.equal(progress.elapsed_ms,1200);assert.equal(progress.current_repair_attempt,1);});

test('assisted work reports user action required and pauses ETA',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));await f.service.record_timing('generate_frame','chatgpt_assisted',1000);const progress=new ProgressTracker(f.service).update(null,{animation_id:'a',stage:'generating',provider:'chatgpt_assisted',user_action_required:true,remaining_operations:{generate_frame:8}});assert.equal(progress.status,'user_action_required');assert.equal(progress.eta_paused,true);assert.equal(progress.estimated_remaining_ms,null);});

test('active pipeline progress survives project hydration',()=>{const workflow=globalThis.SpritedWorkflow,state=workflow.empty(),src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XyVZ5wAAAABJRU5ErkJggg==';workflow.setReference(state,{src,name:'Fixture'});const run=workflow.create(state,'IDLE');run.pipeline_progress={animation_id:run.id,current_stage:'generating',progress_percent:25,elapsed_ms:400};state.animation_runs[0]=run;const restored=workflow.hydrate(JSON.parse(JSON.stringify(state)));assert.deepEqual(restored.animation_runs[0].pipeline_progress,run.pipeline_progress);});
