import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {GeminiImageProvider} from '../automation/gemini-image-provider.mjs';
import {Service,failure} from '../automation/service.mjs';
import {tools} from '../automation/contracts.mjs';
await import('../public/character-workflow.js');

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XyVZ5wAAAABJRU5ErkJggg==','base64');
const config={enabled:true,api_key_env:'SPRITED_TEST_GEMINI_KEY',model:'gemini-3.1-flash-image',default_resolution:'1K',timeout_ms:5000};
const resolver=async()=>({bytes:png,mime_type:'image/png'});
const okFetch=(calls=[])=>async(url,options)=>{calls.push({url,options,body:JSON.parse(options.body)});return {ok:true,json:async()=>({id:'int_mock_1',status:'completed',steps:[{type:'model_output',content:[{type:'image',mime_type:'image/png',data:png.toString('base64')}]}]})};};

test('Gemini provider validates configuration and reports a missing key cleanly',async()=>{
  assert.throws(()=>new GeminiImageProvider({...config,api_key:'secret'}),/environment variable/);assert.throws(()=>new GeminiImageProvider({...config,default_resolution:'8K'}),/0.5K, 1K, 2K, or 4K/);
  const provider=new GeminiImageProvider(config,{environment:{},assetResolver:resolver,fetchImpl:okFetch()});await assert.rejects(()=>provider.generate_frame({frame_index:0,assets:{reference:'character:c'}}),/not configured in SPRITED_TEST_GEMINI_KEY/);assert.equal(provider.status().free_tier_available,false);
});

test('Gemini generate_frame maps reference and neighbors to one image-only interaction',async()=>{
  const calls=[],provider=new GeminiImageProvider(config,{environment:{SPRITED_TEST_GEMINI_KEY:'AIza-test-generate'},assetResolver:resolver,fetchImpl:okFetch(calls)}),result=await provider.generate_frame({animation_type:'WALKING',frame_index:3,total_frame_count:8,direction:'right',required_output_size:[256,256],background_requirement:'transparent',instruction:'Advance the right leg.',assets:{reference:'character:c',previous:'frame:p',next:'frame:n'}});
  assert.equal(result.provider,'gemini_api');assert.equal(result.format,'png');assert.equal(calls.length,1);assert.equal(calls[0].url,'https://generativelanguage.googleapis.com/v1beta/interactions');assert.equal(calls[0].body.model,'gemini-3.1-flash-image');assert.deepEqual(calls[0].body.response_format,{type:'image',mime_type:'image/png',aspect_ratio:'1:1',image_size:'1K'});assert.deepEqual(calls[0].body.input.slice(0,-1).map(part=>part.type),['image','image','image']);assert.match(calls[0].body.input.at(-1).text,/frame 4 of 8/i);assert.match(calls[0].body.input.at(-1).text,/Input image order: reference, previous, next/);assert.equal(result.provider_metadata.free_tier_available,false);
});

test('Gemini edit_frame includes current/reference/neighbors and sanitizes errors',async()=>{
  const calls=[],secret='custom-gemini-secret',provider=new GeminiImageProvider(config,{environment:{SPRITED_TEST_GEMINI_KEY:secret},assetResolver:resolver,fetchImpl:okFetch(calls)});await provider.edit_frame({animation_type:'ATTACK',frame_index:2,total_frame_count:8,required_output_size:[256,256],repair_reasons:['direction_flip'],repair_issue_descriptions:['Weapon points backward.'],assets:{current:'frame:c',reference:'character:r',previous:'frame:p',next:'frame:n'}});assert.equal(calls[0].body.input.filter(part=>part.type==='image').length,4);assert.match(calls[0].body.input.at(-1).text,/Input image order: current, reference, previous, next/);assert.match(calls[0].body.input.at(-1).text,/direction_flip; Weapon points backward/);
  const failed=new GeminiImageProvider(config,{environment:{SPRITED_TEST_GEMINI_KEY:secret},assetResolver:resolver,fetchImpl:async()=>({ok:false,status:401,json:async()=>({error:{message:`Rejected ${secret} and AIzaVisibleTest`}})})});let caught;try{await failed.generate_frame({frame_index:0,assets:{reference:'character:r'}});}catch(error){caught=error;}const output=failure(caught),serialized=JSON.stringify(output);assert.equal(serialized.includes(secret),false);assert.equal(serialized.includes('AIzaVisibleTest'),false);assert.equal('stack' in output,false);assert.match(output.errors[0],/\[redacted\]/);
});

test('Gemini mocked output stores one frame and repairs through existing stable-ID flow',async()=>{
  const root=await mkdtemp(path.join(tmpdir(),'sprited-gemini-')),calls=[],run={id:'animation-1',character_profile_id:'character-1',animation_type:'WALKING',image_provider_id:'gemini_api',provider_usage:{paid_generations:0,paid_repairs:0},options:{output_frames:8,canvas_width:256,canvas_height:256,background_mode:'key',background:'#00ff00'},recipe_snapshot:{default_output_frame_count:8},frame_records:[]},plan={repair_plan_id:'repair-1',status:'active',repaired_frame_indexes:[],frames_to_repair:[{frame_index:3,frame_id:null,reasons:['direction_flip'],issue_descriptions:['Weapon points backward.']}]};
  try{
    const provider=new GeminiImageProvider(config,{environment:{SPRITED_TEST_GEMINI_KEY:'AIza-service-test'},assetResolver:resolver,fetchImpl:okFetch(calls)}),service={root,imageProviders:{gemini_api:provider},defaultImageProvider:'external_manual',providerPolicy:{default_provider:'gemini_api',allow_paid_providers:true,require_confirmation_for_paid_request:true,max_paid_image_generations_per_animation:20,max_paid_repair_generations_per_animation:3},page:{evaluate:async()=>({width:1,height:1})},persist:async()=>{},directory:async relative=>{const dir=path.join(root,relative);await mkdir(dir,{recursive:true});return dir;},input:async relative=>path.join(root,relative)};
    service.core=async(operation,args)=>{if(operation==='workflow/animation/status')return structuredClone(run);if(operation==='workflow/animation/store-frame'){if(args.replace){const current=run.frame_records.find(frame=>frame.frame_id===args.record.frame_id);Object.assign(current,args.record,{frame_index:current.frame_index,created_at:current.created_at});return Object.fromEntries(Object.entries(current).filter(([key])=>key!=='storage_path'));}run.frame_records.push(args.record);return Object.fromEntries(Object.entries(args.record).filter(([key])=>key!=='storage_path'));}if(operation==='workflow/animation/record-provider-usage'){run.provider_usage[args.counter]++;return run.provider_usage;}if(operation==='workflow/repair/find')return {animation_id:run.id,plan};if(operation==='workflow/animation/record-repair-frame'){if(!plan.repaired_frame_indexes.includes(args.frame_index))plan.repaired_frame_indexes.push(args.frame_index);return plan;}throw Error(`Unexpected core operation: ${operation}`);};service.storeProviderFrame=(args,replace)=>Service.prototype.storeProviderFrame.call(service,args,replace);
    const first=await service.storeProviderFrame({animation_id:run.id,frame_index:0,provider:'gemini_api',confirm_paid_request:true},false);assert.equal(first.provider,'gemini_api');assert.equal(first.provider_metadata.model,'gemini-3.1-flash-image');assert.equal(run.frame_records.length,1);for(let index=1;index<8;index++)await service.storeProviderFrame({animation_id:run.id,frame_index:index,provider:'gemini_api',confirm_paid_request:true},false);plan.frames_to_repair[0].frame_id=run.frame_records[3].frame_id;const stableId=run.frame_records[3].frame_id,repaired=await Service.prototype.submitRepairFrame.call(service,{repair_plan_id:plan.repair_plan_id,frame_index:3,provider:'gemini_api',confirm_paid_request:true});assert.equal(repaired.frame.frame_id,stableId);assert.equal(repaired.frame.provider,'gemini_api');assert.deepEqual(repaired.repaired_frame_indexes,[3]);assert.equal(calls.length,9);assert.equal(calls.at(-1).body.input.filter(part=>part.type==='image').length,4);assert.match(calls.at(-1).body.input.at(-1).text,/Weapon points backward/);assert.equal(tools.length,22);assert.ok(tools.find(tool=>tool.name==='submit_repair_frame').inputSchema.properties.provider.enum.includes('gemini_api'));
  }finally{await rm(root,{recursive:true,force:true});}
});

test('redo persistence regression remains fixed for Gemini frame records',()=>{
  const workflow=globalThis.SpritedWorkflow,state=workflow.empty(),src=`data:image/png;base64,${png.toString('base64')}`,character=workflow.setReference(state,{src,name:'Gemini Redo'}),job=workflow.library(state,'jobs/create',{character_id:character.id,animation_type:'WALKING',duration:1.6,loop:true,frames:8,sampling:'uniform'}),original=workflow.get(state,job.attempt_id);original.frame_records=[{frame_id:'stable-gemini-frame',character_id:character.id,animation_id:original.id,frame_index:0,format:'png',width:1,height:1,created_at:new Date().toISOString(),provider:'gemini_api',storage_path:'SPRITED_DATA/frame.png'}];original.source_frame_paths=['SPRITED_DATA/frame.png'];const redoJob=workflow.library(state,'attempts/redo',{id:original.id}),reloaded=workflow.hydrate(JSON.parse(JSON.stringify(state))),redo=workflow.get(reloaded,redoJob.attempt_id);assert.equal(workflow.get(reloaded,original.id).frame_records[0].frame_id,'stable-gemini-frame');assert.deepEqual(redo.frame_records,[]);assert.deepEqual(redo.source_frame_paths,[]);assert.equal(redo.parent_run_id,original.id);
});
