import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,stat} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
const {Service}=await import(process.env.SPRITED_SERVICE_MODULE?pathToFileURL(process.env.SPRITED_SERVICE_MODULE).href:'../automation/service.mjs');
const {serve}=await import(process.env.SPRITED_HTTP_MODULE?pathToFileURL(process.env.SPRITED_HTTP_MODULE).href:'../automation/http.mjs');
const root=path.resolve(process.env.SPRITED_TEST_WORKSPACE);await mkdir(root,{recursive:true});
await writeFile(path.join(root,'fixture.webm'),await readFile(process.env.SPRITED_TEST_VIDEO));
let service=new Service(root),http,browser;let characterId,attemptId,jobId;
const call=async(action,args={})=>{const r=await service.call(action,args);assert.equal(r.success,true,JSON.stringify(r));return r;};
try{
  await service.init();
  const src=await service.page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d');x.fillStyle='#ff5533';x.fillRect(22,4,20,56);return c.toDataURL();});await writeFile(path.join(root,'fixture.png'),Buffer.from(src.split(',')[1],'base64'));
  const c=(await call('character/create',{name:'Test Guardian (synthetic reference)',path:'fixture.png'})).result;characterId=c.id;
  const panda=(await call('character/create',{name:'Test Panda',path:'fixture.png'})).result;
  assert.equal((await call('character/list')).result.length,2);
  const j=(await call('jobs/create',{character_id:c.id,animation_type:'WALKING',duration:1.5,loop:true,frames:8,sampling:'smart'})).result;jobId=j.job_id;attemptId=j.attempt_id;
  assert.equal(j.motion_template.phases.length,8);assert.equal(j.status,'QUEUED');assert.equal(j.duration,1.5);
  const [claim,duplicate]=await Promise.all([service.call('jobs/claim',{id:jobId,agent:'integration-test'}),service.call('jobs/claim',{id:jobId,agent:'other-agent'})]);assert.equal(claim.success,true);assert.equal(duplicate.success,false);
  assert.equal((await service.call('jobs/submit-result',{id:jobId,claim_token:'wrong',path:'fixture.webm',provider:'synthetic-test-NOT-AI'})).success,false);
  await call('jobs/release',{id:jobId,claim_token:claim.result.claim_token});const again=(await call('jobs/claim',{id:jobId,agent:'integration-test'})).result;
  const submission=await call('jobs/submit-result',{id:jobId,claim_token:again.claim_token,path:'fixture.webm',provider:'synthetic-test-NOT-AI',model:'none',seed:'fixture'});
  assert.equal(submission.status,'RESULT_SUBMITTED');await stat(submission.output_paths[0]);
  assert.equal((await call('status')).result.frame_count,0,'Video receipt does not extract frames');
  assert.equal((await call('animation/status',{id:attemptId})).result.editor_snapshot,undefined);
  await call('animation/approve',{id:attemptId});
  const redo=(await call('attempts/redo',{id:attemptId})).result;assert.notEqual(redo.attempt_id,attemptId);assert.equal(redo.duration,1.5);assert.equal(redo.variation_request.previous_attempt_id,attemptId);
  const eight=await call('spritesheet/create',{id:attemptId,frames:8,sampling:'smart'});assert.equal(eight.result.spritesheets[0].frame_count,8);assert.match(eight.warnings.join(' '),/UNIFORM/);
  assert.equal(eight.output_paths.filter(p=>/frame_\d+\.png$/.test(p)).length,8);
  const twentyFour=await call('spritesheet/create',{id:attemptId,frames:24,sampling:'uniform'});assert.equal(twentyFour.result.spritesheets.length,2);assert.equal(twentyFour.result.spritesheets[1].frame_count,24);
  assert.equal(twentyFour.result.source_video_path,eight.result.source_video_path);assert.equal((await call('status')).result.frame_count,0,'sheet creation preserves editor');
  assert.equal((await service.call('character/delete',{id:panda.id,confirm_name:'Wrong'})).success,false);
  await call('character/delete',{id:panda.id,confirm_name:panda.name});assert.equal((await call('character/list')).result.length,1);assert.equal((await call('character/trash')).result.length,1);await call('character/restore',{id:panda.id});assert.equal((await call('character/list')).result.length,2);
  await service.close();service=new Service(root);await service.init();assert.equal((await call('character/list')).result.length,2);assert.equal((await call('animation/status',{id:attemptId})).result.spritesheets.length,2);assert.equal((await call('jobs/get',{id:jobId})).result.status,'RESULT_SUBMITTED');
  http=await serve(service,0,'library-test-token');
  const cli=process.env.SPRITED_CLI||path.resolve('automation/cli.mjs');
  const child=spawn(process.execPath,[cli,'mcp','--api',`http://127.0.0.1:${http.port}`],{env:{...process.env,SPRITED_TOKEN:'library-test-token'}});let sequence=0;const waiting=new Map();let stderr='';child.stderr.on('data',b=>stderr+=b);
  createInterface({input:child.stdout}).on('line',line=>{const m=JSON.parse(line);waiting.get(m.id)?.(m);waiting.delete(m.id);});
  const rpc=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence,t=setTimeout(()=>reject(Error('MCP proxy timeout: '+stderr)),30000);waiting.set(id,m=>{clearTimeout(t);resolve(m);});child.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n');});
  try {await rpc('initialize');const listed=await rpc('tools/list');assert.ok(listed.result.tools.some(t=>t.name==='sprited_claim_generation_job'));const claim=await rpc('tools/call',{name:'sprited_claim_generation_job',arguments:{id:redo.job_id,agent:'MCP-proxy-test'}});assert.equal(claim.result.structuredContent.success,true);const release=await rpc('tools/call',{name:'sprited_release_generation_job',arguments:{id:redo.job_id,claim_token:claim.result.structuredContent.result.claim_token}});assert.equal(release.result.structuredContent.success,true);}finally{child.stdin.end();await new Promise(r=>child.on('exit',r));}
  const {chromium}=await import(pathToFileURL(process.env.SPRITED_PLAYWRIGHT).href);browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${http.port}/ui/#library-test-token`);await page.waitForSelector('#libraryDialog[open]');await page.waitForFunction(()=>document.querySelector('#libraryCharacters').options.length===2);
  await page.locator('#libraryCharacters').selectOption(characterId);await page.locator('#libraryAttempts').selectOption(attemptId);await page.waitForFunction(()=>document.querySelector('#libraryVideoPreview').readyState>=2);
  await page.screenshot({path:path.join(root,'library.png')});
  await page.locator('#libraryMoreExports > summary').click();await page.locator('#libraryEditor').click();await page.waitForFunction(()=>!document.querySelector('#libraryDialog').open);assert.equal((await page.evaluate(()=>window.SpritedCore.dispatch('status'))).frame_count,24);
  assert.deepEqual(errors,[]);
  await call('character/delete',{id:panda.id,confirm_name:panda.name});assert.equal((await service.call('character/purge',{id:panda.id,confirm_name:panda.name,confirm_delete:'no'})).success,false);
  await call('character/purge',{id:panda.id,confirm_name:panda.name,confirm_delete:'DELETE PERMANENTLY'});assert.equal((await call('character/trash')).result.length,0);assert.equal((await call('character/list')).result.length,1);
  await assert.rejects(()=>stat(path.join(root,panda.reference_image_path)),{code:'ENOENT'});
  console.log('PASS persistent multi-character library/restart, exclusive job claims/release, scoped video submission, video-before-extraction, approve/REDO history, same-video 8 and 24 PNG sets, SMART fallback, Trash/restore, connected GUI/video/editor. Synthetic fixture only; NO AI generation acceptance claimed.');
}finally{await browser?.close();if(http)await new Promise(r=>http.server.close(r));await service.close();}
