import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Service} from '../automation/service.mjs';
import {createMcpSession} from '../automation/mcp.mjs';

const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XyVZ5wAAAABJRU5ErkJggg==';
const webp='UklGRiIAAABXRUJQVlA4IBYAAAAwAQCdASoBAAEAAUAmJaQAA3AA/v89WAAAAA==';
const root=await mkdtemp(path.join(os.tmpdir(),'sprited-character-mcp-'));
let service,session;
try{
  service=await new Service(root).init();
  session=createMcpSession(service);
  const rpc=async(method,params={})=>session.handle({jsonrpc:'2.0',id:Math.random(),method,params});
  await rpc('initialize',{clientInfo:{name:'character-ingestion-test'}});
  const listed=await rpc('tools/list');
  assert.equal(listed.result.tools.length,33);
  const registerTool=listed.result.tools.find(tool=>tool.name==='register_character');
  const setReferenceTool=listed.result.tools.find(tool=>tool.name==='set_character_reference');
  assert.ok(registerTool);
  assert.ok(setReferenceTool);
  assert.deepEqual(registerTool._meta,{'openai/fileParams':['reference_image']});
  assert.deepEqual(setReferenceTool._meta,{'openai/fileParams':['reference_image']});
  assert.equal(registerTool.inputSchema.properties.reference_image.anyOf[0].properties.download_url.type,'string');
  const register=await rpc('tools/call',{name:'register_character',arguments:{name:'Ingestion Test',id:'ingestion-test',description:'focused test',reference_image:png,reference_format:'png'}});
  assert.equal(register.result.isError,false,JSON.stringify(register));
  const created=register.result.structuredContent;
  assert.equal(created.result.character_id,'ingestion-test');
  assert.equal(created.result.reference_image.format,'png');
  assert.equal(created.result.reference_image.managed,true);
  const listedCharacters=await rpc('tools/call',{name:'list_characters',arguments:{}});
  assert.equal(listedCharacters.result.structuredContent.result.length,1);
  assert.equal(listedCharacters.result.structuredContent.result[0].id,'ingestion-test');
  const selected=await rpc('tools/call',{name:'get_character',arguments:{id:'ingestion-test'}});
  assert.equal(selected.result.isError,false,JSON.stringify(selected));
  assert.equal(selected.result.content[1].type,'image');
  assert.equal(selected.result.content[1].mimeType,'image/png');
  const duplicate=await rpc('tools/call',{name:'register_character',arguments:{name:'Duplicate',id:'ingestion-test',reference_image:png,reference_format:'png'}});
  assert.equal(duplicate.result.isError,true);
  assert.match(duplicate.result.structuredContent.errors[0],/already exists/);
  const originalFetch=globalThis.fetch;
  globalThis.fetch=async()=>new Response(Buffer.from(webp,'base64'),{status:200,headers:{'content-type':'image/webp'}});
  const updated=await rpc('tools/call',{name:'set_character_reference',arguments:{character_id:'ingestion-test',reference_image:{download_url:'https://files.oaiusercontent.com/test.webp',file_id:'file_test',file_name:'test.webp',mime_type:'image/webp'},reference_format:'webp'}});
  globalThis.fetch=originalFetch;
  assert.equal(updated.result.isError,false,JSON.stringify(updated));
  assert.equal(updated.result.structuredContent.result.character_id,'ingestion-test');
  assert.equal(updated.result.structuredContent.result.reference_image.format,'webp');
  const selectedWebp=await rpc('tools/call',{name:'get_character',arguments:{id:'ingestion-test'}});
  assert.equal(selectedWebp.result.content[1].mimeType,'image/webp');
  assert.equal(selectedWebp.result.structuredContent.result.notes,'focused test');
  const missing=await rpc('tools/call',{name:'set_character_reference',arguments:{character_id:'missing',reference_image:png,reference_format:'png'}});
  assert.equal(missing.result.isError,true);
  const invalid=await rpc('tools/call',{name:'register_character',arguments:{name:'Invalid',reference_image:'not-an-image',reference_format:'png'}});
  assert.equal(invalid.result.isError,true);
  await session.close();session=null;await service.close();service=null;
  service=await new Service(root).init();
  const persisted=await service.call('agent/get-character',{id:'ingestion-test'});
  assert.equal(persisted.success,true,JSON.stringify(persisted));
  assert.equal(persisted.result.name,'Ingestion Test');
  const persistedAsset=await service.readContentReference(persisted.result.content_reference);
  assert.equal(persistedAsset.mime_type,'image/webp');
  console.log('PASS: register_character, set_character_reference, discovery, safety cases, and restart persistence');
}finally{
  await session?.close().catch(()=>{});
  await service?.close().catch(()=>{});
  await rm(root,{recursive:true,force:true});
}
