import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createActionMotionSpec,createMotionTimeline,createSamplingPlan,createMotionObservation,createTransitionObservation,deriveTransitionObservations,compareIntendedAndObservedMotion} from '../automation/motion-engine.mjs';
import {WALKING_ACTION_MOTION_SPEC,WALKING_PHASE_SPECS,buildPosePlan} from '../automation/pose-planner.mjs';
import {inspectPlayback} from '../automation/temporal-inspector.mjs';

const attackSpec=()=>createActionMotionSpec({action_type:'ATTACK',cyclic:false,start_state:'ready',end_state:'recovery',key_poses:[['ready',0],['anticipation',.18],['wind-up',.38],['acceleration',.55],['impact',.65],['follow-through',.8],['recovery',1]].map(([id,timeline_position])=>({id,name:id,timeline_position,is_anchor:['ready','impact','recovery'].includes(id)})),motion_events:[{id:'acceleration-event',name:'Acceleration',timeline_position:.55,type:'acceleration'},{id:'impact-event',name:'Impact',timeline_position:.65,type:'impact'}],important_anchor_pose_ids:['ready','impact','recovery'],body_mechanics:{torso:'rotates through strike'},anticipation:{range:[.18,.38]},action_impact_point:{timeline_position:.65},follow_through:{range:[.65,.8]},recovery:{range:[.8,1]},sampling_intent:{mode:'anchor-preserving'},action_specific_mechanics:{weapon_trajectory:'back-to-forward arc'}});

const explicitTransitions=plan=>plan.samples.slice(0,plan.samples.length-(plan.cyclic?0:1)).map((sample,index)=>createTransitionObservation({source_frame:sample.frame_index,target_frame:plan.samples[(index+1)%plan.samples.length].frame_index,timeline_interval:[sample.timeline_position,index===plan.samples.length-1&&plan.cyclic?1:plan.samples[(index+1)%plan.samples.length].timeline_position],expected_timeline_direction:'forward',observed_movement_direction:'forward',continuity_confidence:.95,duplicate_near_duplicate_likelihood:0,reversal_likelihood:0,skipped_motion_likelihood:0,loop_seam_discontinuity:0,observation_confidence:.95}));

test('ActionMotionSpec and MotionTimeline describe normalized action mechanics before frames',()=>{const spec=attackSpec(),timeline=createMotionTimeline(spec);assert.equal(spec.schema,'action-motion-spec/v1');assert.equal(spec.action_type,'ATTACK');assert.equal(spec.key_poses.at(-1).timeline_position,1);assert.ok(spec.motion_events.some(item=>item.id==='impact-event'));assert.equal(spec.motion_segments.length,6);assert.equal(timeline.schema,'motion-timeline/v1');assert.equal(timeline.start,0);assert.equal(timeline.end,1);assert.ok(spec.motion_segments.every(segment=>segment.repair_range.length===2));});

test('SamplingPlan changes frame samples without redefining ActionMotionSpec',()=>{const spec=attackSpec(),six=createSamplingPlan(spec,{frameCount:6}),twelve=createSamplingPlan(spec,{frameCount:12}),eventAware=createSamplingPlan(spec,{frameCount:4,mode:'event-aware'});assert.equal(six.frame_count,6);assert.equal(twelve.frame_count,12);assert.deepEqual(spec.key_poses.map(item=>item.timeline_position),[0,.18,.38,.55,.65,.8,1]);assert.ok(twelve.samples.some(sample=>sample.timeline_position===.65&&sample.is_anchor));assert.ok(eventAware.samples.some(sample=>sample.timeline_position===.55));assert.ok(twelve.samples.every(sample=>sample.motion_state_before&&sample.motion_state_after&&sample.motion_segment_id));});

test('synthetic ATTACK uses the shared engine and keeps mechanics action-specific',async()=>{const spec=attackSpec(),plan=createSamplingPlan(spec,{frameCount:12}),source=await readFile(new URL('../automation/motion-engine.mjs',import.meta.url),'utf8');assert.equal(plan.action_type,'ATTACK');assert.equal(spec.action_specific_mechanics.weapon_trajectory,'back-to-forward arc');assert.doesNotMatch(source,/WALKING_PHASE_SPECS|WalkEngine|AttackEngine/);});

test('MotionObservation preserves unknowns instead of inventing values',()=>{const observation=createMotionObservation({frame_index:2,timeline_position:.38,body_center:{x:.4,y:.5},observation_confidence:.9});assert.equal(observation.body_rotation,null);assert.equal(observation.major_limb_positions,null);assert.ok(observation.unknown_fields.includes('weapon_tool_position'));});

test('TransitionObservation is derived for every adjacent sample and cyclic seam',()=>{const plan=createSamplingPlan(WALKING_ACTION_MOTION_SPEC,{frameCount:8}),observations=Object.fromEntries(plan.samples.map(sample=>[sample.frame_index,createMotionObservation({frame_index:sample.frame_index,timeline_position:sample.timeline_position,recognized_key_pose_id:sample.key_pose_id,body_center:{x:sample.frame_index,y:0},major_limb_positions:{phase:sample.key_pose_id},motion_direction:'forward',pose_confidence:.95,observation_confidence:.95})])),transitions=deriveTransitionObservations(plan,observations);assert.equal(transitions.length,8);assert.deepEqual([transitions.at(-1).source_frame,transitions.at(-1).target_frame],[7,0]);assert.deepEqual(transitions.at(-1).timeline_interval,[.875,1]);});

test('intended versus observed validation detects chronology, reversal, skip, duplicate and insufficient evidence',()=>{const spec=attackSpec(),plan=createSamplingPlan(spec,{frameCount:8}),base=explicitTransitions(plan);assert.ok(compareIntendedAndObservedMotion(spec,plan,{},base).every(item=>item.status==='PASS'));for(const [field,issue] of [['reversal_likelihood','reversed_motion'],['skipped_motion_likelihood','skipped_motion'],['duplicate_near_duplicate_likelihood','repeated_pose']]){const changed=structuredClone(base);changed[2][field]=.9;const verdict=compareIntendedAndObservedMotion(spec,plan,{},changed)[2];assert.equal(verdict.status,'FAIL');assert.ok(verdict.detected_issues.includes(issue));}const chronology=structuredClone(base);chronology[1].timeline_interval=[.9,.1];assert.ok(compareIntendedAndObservedMotion(spec,plan,{},chronology)[1].detected_issues.includes('chronological_progression'));const missing=structuredClone(base);missing[1].observation_confidence=null;assert.equal(compareIntendedAndObservedMotion(spec,plan,{},missing)[1].status,'INSUFFICIENT_OBSERVATION');});

test('Temporal Inspector consumes generic observations and validates the cyclic seam',()=>{const run={animation_type:'WALKING',options:{output_frames:8,loop:true},recipe_snapshot:{loop:true,default_output_frame_count:8,motion_template:{phases:WALKING_PHASE_SPECS.map(item=>item.phase_name)}}},plan=buildPosePlan(run),observations=Object.fromEntries(plan.sampling_plan.samples.map(sample=>{const keyPose=plan.action_motion_spec.key_poses.find(item=>item.id===sample.key_pose_id);return [sample.frame_index,createMotionObservation({frame_index:sample.frame_index,timeline_position:sample.timeline_position,recognized_key_pose_id:sample.key_pose_id,body_center:{x:sample.frame_index,y:0},major_limb_positions:{phase:sample.key_pose_id},motion_direction:'forward',pose_confidence:.95,observation_confidence:.95,...keyPose.expected_observation})];})),result=inspectPlayback(plan.frames,{posePlan:plan,motionObservations:observations,transitionObservations:explicitTransitions(plan.sampling_plan)});assert.equal(result.passed,true);assert.equal(result.transition_map.length,8);assert.equal(result.loop_status,'PASS');assert.ok(result.anchor_verdicts.every(item=>item.status==='PASS'));});

test('declared WALKING mechanics reject an observed key-pose mismatch',()=>{const run={animation_type:'WALKING',options:{output_frames:8,loop:true},recipe_snapshot:{loop:true,default_output_frame_count:8}},plan=buildPosePlan(run),observations=Object.fromEntries(plan.sampling_plan.samples.map(sample=>{const keyPose=plan.action_motion_spec.key_poses.find(item=>item.id===sample.key_pose_id);return [sample.frame_index,{frame_index:sample.frame_index,timeline_position:sample.timeline_position,recognized_key_pose_id:sample.key_pose_id,pose_confidence:.95,observation_confidence:.95,...keyPose.expected_observation}];}));observations[0].weight_direction={state:'wrong support'};const result=inspectPlayback(plan.frames,{posePlan:plan,motionObservations:observations,transitionObservations:explicitTransitions(plan.sampling_plan)});assert.equal(result.passed,false);assert.ok(result.frame_verdicts[0].detected_issues.includes('weight_direction_mismatch'));});
