import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import {mkdtemp,rm} from 'node:fs/promises';
import {createMotionMemory,setMotionProperties,applyHumanMotionLock,detectMotionLockRegressions,MOTION_LOCK_STATES} from '../automation/motion-lock.mjs';
import {ExperienceService} from '../automation/experience-service.mjs';
import {prepareAssistedRequest} from '../automation/chatgpt-assisted.mjs';

test('motion properties lock independently and low confidence stays preserve/unknown',()=>{let memory=createMotionMemory();memory=setMotionProperties(memory,2,{lead_leg:'left',pelvis_height:'neutral'},{confidence:.95,lastValidationScore:96});memory=setMotionProperties(memory,2,{arm_counter_swing:'confirmed'},{confidence:.4});assert.equal(memory.frames[2].lead_leg.status,MOTION_LOCK_STATES.LOCKED_CORRECT);assert.equal(memory.frames[2].arm_counter_swing.status,MOTION_LOCK_STATES.UNKNOWN);});
test('visual repair prompt preserves locked motion properties',()=>{const run={id:'r',animation_type:'WALKING',options:{output_frames:8,canvas_width:256,canvas_height:256},recipe_snapshot:{default_output_frame_count:8,motion_template:{phases:['left contact','left down','left passing','left up','right contact','right down','right passing','right up']}},frame_records:Array.from({length:8},(_,frame_index)=>({frame_index,frame_id:`f${frame_index}`})),motion_memory:{frames:{4:{lead_leg:{status:'LOCKED_CORRECT',value:'right'},pelvis_height:{status:'PRESERVE_MOTION',value:'neutral'}}}}};const request=prepareAssistedRequest({run,frameIndex:4,repairPlan:{frames_to_repair:[{frame_index:4,reasons:['shield_position'],issue_descriptions:['shield misplaced'],pose:run.recipe_snapshot.motion_template.phases[4]?null:null,repair_plan_details:{must_change:['shield position'],must_not_change:['right contact'],expected_measurable_improvement:['shield alignment']}}]}});assert.match(request.prompt,/MUST PRESERVE validated motion/i);assert.match(request.prompt,/lead_leg=right/i);});
test('locked motion regression is detected and human lock is authoritative',()=>{let memory=createMotionMemory();memory=setMotionProperties(memory,1,{paired_frame_relation:'correct',lead_leg:'left'},{confidence:.9});let regressions=detectMotionLockRegressions(memory,1,{paired_frame_relation:'broken',lead_leg:'right'});assert.equal(regressions.length,2);memory=applyHumanMotionLock(memory,1,{pelvis_height:'fixed'});assert.equal(memory.frames[1].pelvis_height.status,MOTION_LOCK_STATES.LOCKED_CORRECT);});
test('accepted motion memory persists across restart',async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'sprited-motion-lock-'));t.after(()=>rm(root,{recursive:true,force:true}));const options={experiencePath:path.join(root,'experience.json'),timingPath:path.join(root,'timing.json')},service=await new ExperienceService(options).init();await service.record_motion_lock({animation_id:'walk',frame_index:3,properties:{lead_leg:{status:'LOCKED_CORRECT',value:'left'}},source:'validator',confidence:.95});const restarted=await new ExperienceService(options).init();assert.equal(restarted.experiences.motion_locks.length,1);});
