import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {buildPosePlan} from '../automation/pose-planner.mjs';
import {createMotionMemory,setMotionProperties,MOTION_LOCK_STATES} from '../automation/motion-lock.mjs';
import {createRepairPlan} from '../automation/repair-orchestrator.mjs';
import {Service,buildMotionGenerationContext,shouldCreateAutomaticDebugSnapshot} from '../automation/service.mjs';

const baseRun=()=>{const run={id:'walk',animation_type:'WALKING',character_profile_id:'character',options:{output_frames:8,loop:true,background:'#00ff00'},recipe_snapshot:{loop:true,default_output_frame_count:8,motion_template:{phases:['left contact','left down','left passing','left up','right contact','right down','right passing','right up']}},frame_records:Array.from({length:8},(_,frame_index)=>({frame_index,frame_id:`f${frame_index}`})),repair_plans:[]};run.pose_plan=buildPosePlan(run);return run;};
const goodObservations=run=>Object.fromEntries(run.pose_plan.sampling_plan.samples.map(sample=>{const keyPose=run.pose_plan.action_motion_spec.key_poses.find(item=>item.id===sample.key_pose_id);return [sample.frame_index,{timeline_position:sample.timeline_position,recognized_key_pose_id:sample.key_pose_id,body_center:{x:sample.frame_index,y:0},major_limb_positions:{phase:sample.key_pose_id},motion_direction:'forward',pose_confidence:.95,observation_confidence:.95,...keyPose?.expected_observation}];}));
const passingTemporal=()=>({status:'PASS',passed:true,motion_approved:true,transition_map:Array.from({length:8},(_,from_frame)=>({from_frame,to_frame:(from_frame+1)%8,status:'PASS',confidence:.95})),motion_observations:Object.fromEntries([0,2,4,6].map(frame_index=>[frame_index,{timeline_position:frame_index/8,recognized_key_pose_id:['left-contact','left-passing','right-contact','right-passing'][frame_index/2],body_center:{x:frame_index,y:0},pose_confidence:.95,observation_confidence:.95}])),anchor_verdicts:[0,2,4,6].map(frame_index=>({frame_index,status:'PASS',confidence:.95,pose_matches:true,inbound_status:'PASS',outbound_status:'PASS'}))});

test('breakdown motion context contains both surrounding anchors',()=>{const run=baseRun(),records=run.frame_records.filter(frame=>[0,4,2,6].includes(frame.frame_index)),context=buildMotionGenerationContext(run,records,1);assert.equal(context.motionContext.target_phase_spec.phase_name,'Left Down');assert.equal(context.motionContext.previous_anchor.phase_spec.phase_name,'Left Contact');assert.equal(context.motionContext.previous_anchor.reference,'frame:f0');assert.equal(context.motionContext.next_anchor.phase_spec.phase_name,'Left Passing');assert.equal(context.motionContext.next_anchor.reference,'frame:f2');});

test('paired anchor context is available after its opposite anchor is generated',()=>{const run=baseRun(),context=buildMotionGenerationContext(run,[run.frame_records[0]],4);assert.equal(context.motionContext.target_phase_spec.phase_name,'Right Contact');assert.equal(context.motionContext.paired_phase_spec.phase_name,'Left Contact');assert.equal(context.motionContext.paired_anchor_reference,'frame:f0');});

test('technical validation automatically persists all cyclic temporal transitions',async()=>{const run=baseRun(),recorded=[];let lockCalls=0;const service={decodeStoredFrames:async()=>({run,frames:[]}),recordProgress:async()=>{},observed:async()=>({passed:true,score:100,issues:[],bad_frames:[],loop_validation:{passed:true,loop_score:100}}),core:async(operation,args)=>{recorded.push([operation,args]);if(operation==='workflow/animation/record-temporal-inspection')run.temporal_inspection=args.temporal_inspection;if(operation==='workflow/animation/record-validation')run.technical_validation=args.validation;return args;},lockValidatedAnchors:async()=>{lockCalls++;}};const result=await Service.prototype.runTechnicalValidation.call(service,'walk',{motionObservations:goodObservations(run)});assert.equal(result.motion_approved,true);assert.deepEqual(result.temporal_validation.transition_map.map(item=>[item.from_frame,item.to_frame]),[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,0]]);assert.equal(run.temporal_inspection.passed,true);assert.equal(lockCalls,1);assert.ok(recorded.some(([operation])=>operation==='workflow/animation/record-temporal-inspection'));});

test('missing observations persist an insufficient state and never lock anchors',async()=>{const run=baseRun();let lockResult='not-called';const service={decodeStoredFrames:async()=>({run,frames:[]}),recordProgress:async()=>{},observed:async()=>({passed:true,score:100,issues:[],bad_frames:[],loop_validation:{passed:true,loop_score:100}}),core:async(operation,args)=>{if(operation==='workflow/animation/record-temporal-inspection')run.temporal_inspection=args.temporal_inspection;return args;},lockValidatedAnchors:async(_id,_technical,temporal)=>{lockResult=temporal.passed;}};const result=await Service.prototype.runTechnicalValidation.call(service,'walk');assert.equal(result.passed,true);assert.equal(result.motion_approved,false);assert.equal(result.temporal_validation.status,'INSUFFICIENT_MOTION_OBSERVATION');assert.equal(lockResult,false);});

test('validated primary anchors become locked but generated-only anchors do not',async()=>{const run=baseRun();run.motion_memory=createMotionMemory();let saved=null;const service={core:async(operation,args)=>{if(operation==='workflow/animation/status')return run;if(operation==='workflow/animation/record-motion-memory'){saved=args.motion_memory;run.motion_memory=saved;return saved;}throw Error(operation);},persist:async()=>{}};await Service.prototype.lockValidatedAnchors.call(service,'walk',{passed:true,score:96},passingTemporal());assert.deepEqual(Object.keys(saved.frames).map(Number).sort((a,b)=>a-b),[0,2,4,6]);assert.equal(saved.frames[0].phase_accuracy.status,MOTION_LOCK_STATES.LOCKED_CORRECT);assert.equal(saved.frames[0].body_center.status,MOTION_LOCK_STATES.LOCKED_CORRECT);const generated=baseRun();generated.motion_memory=createMotionMemory();const untouched=await Service.prototype.lockValidatedAnchors.call({core:async()=>generated,persist:async()=>{}},'walk',{passed:true,score:100},{status:'INSUFFICIENT_MOTION_OBSERVATION',passed:false,transition_map:[]});assert.equal(untouched,null);assert.deepEqual(generated.motion_memory.frames,{});});

test('technical and transition success cannot lock an anchor without frame motion evidence',async()=>{const run=baseRun();run.motion_memory=createMotionMemory();const temporal=passingTemporal();delete temporal.motion_observations;const result=await Service.prototype.lockValidatedAnchors.call({core:async()=>run,persist:async()=>{}},'walk',{passed:true,score:100},temporal);assert.deepEqual(result.frames,{});});

test('ordinary visual repair preserves a locked anchor',()=>{const run=baseRun();run.motion_memory=setMotionProperties(createMotionMemory(),0,{phase_accuracy:'Left Contact'},{confidence:.95});run.technical_validation={score:70,issues:[{type:'visual_jump',frame:0,severity:'high'},{type:'visual_jump',frame:1,severity:'high'}]};const plan=createRepairPlan(run);assert.deepEqual(plan.preserved_locked_anchors,[0]);assert.deepEqual(plan.frames_to_repair.map(frame=>frame.frame_index),[1]);});

test('debug snapshots are automatic only for failure paths and explicit diagnostics remain available',()=>{assert.equal(shouldCreateAutomaticDebugSnapshot('ready'),false);assert.equal(shouldCreateAutomaticDebugSnapshot('accepted'),false);assert.equal(shouldCreateAutomaticDebugSnapshot('failed'),true);assert.equal(shouldCreateAutomaticDebugSnapshot('blocked'),true);assert.equal(typeof Service.prototype.debugOutput,'function');});

test('frame storage persists one completion checkpoint instead of generation/import micro-events',async()=>{const source=await readFile(new URL('../automation/service.mjs',import.meta.url),'utf8'),body=source.slice(source.indexOf('async storeProviderFrame('),source.indexOf('async createAttemptFromSpritesheet('));assert.equal((body.match(/recordProgress\(/g)||[]).length,2);assert.doesNotMatch(body,/recordProgress\(run\.id,'importing'/);assert.doesNotMatch(body,/status_message:replace\?`Repairing frame/);assert.match(body,/Frames received/);});
