import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPosePlan,createRepairPlanDetails,validatePairedPoseRelation} from '../automation/pose-planner.mjs';
import {createRepairPlan} from '../automation/repair-orchestrator.mjs';
import {prepareAssistedRequest} from '../automation/chatgpt-assisted.mjs';
import {ExternalManualVisionProvider} from '../automation/semantic-validator.mjs';

const run={id:'walk',animation_type:'WALKING',character_profile_id:'c',options:{output_frames:8,canvas_width:256,canvas_height:256},recipe_snapshot:{default_output_frame_count:8,motion_template:{phases:['left contact','left down','left passing','left up','right contact','right down','right passing','right up']}},frame_records:Array.from({length:8},(_,frame_index)=>({frame_index,frame_id:`f${frame_index}`})),technical_validation:{score:50,issues:[{type:'leg_progression',frame_index:4,severity:'high',description:'wrong lead leg'}]},semantic_validation:null,repair_plans:[]};

test('pose plan pairs opposite gait phases and swaps lead legs',()=>{const plan=buildPosePlan(run);assert.equal(plan.frames[0].animation_phase,'left contact');assert.equal(plan.frames[4].animation_phase,'right contact');assert.equal(plan.frames[0].paired_frame_index,4);assert.equal(plan.frames[4].paired_frame_index,0);assert.equal(plan.frames[0].anatomical_lead_leg,'left');assert.equal(plan.frames[4].anatomical_lead_leg,'right');assert.equal(plan.frames[0].required_paired_relation,'contralateral counterpart; do not preserve identical silhouette');});
test('repair plan carries must-change, preserve, neighbor and paired context',()=>{const plan=createRepairPlan(run),target=plan.frames_to_repair[0];assert.ok(plan.pose_plan);assert.equal(target.paired_frame_index,0);assert.deepEqual(target.repair_plan_details.neighbor_frames,[3,5]);assert.ok(target.repair_plan_details.must_change.some(item=>/lead leg/i.test(item)));assert.ok(target.repair_plan_details.must_not_change.some(item=>/identity/i.test(item)));});
test('prompt uses pose and paired-frame requirements without silhouette over-constraint',()=>{const plan=createRepairPlan(run),request=prepareAssistedRequest({run:{...run,pose_plan:plan.pose_plan},frameIndex:4,repairPlan:plan});assert.match(request.prompt,/Pose Plan: right contact/i);assert.match(request.prompt,/paired contralateral frame/i);assert.match(request.prompt,/Preserve character identity, not the previous body contour/i);assert.equal(request.asset_references.paired,'frame:f0');});
test('paired diagnostics flag same-side repetition',()=>{const plan=buildPosePlan(run),diagnostics=validatePairedPoseRelation(plan,{0:{lead_leg:'left'},4:{lead_leg:'left'}});assert.equal(diagnostics[0].lead_trail_swap_correct,false);assert.equal(diagnostics[0].incorrect_same_side_repetition,true);});
test('repair details prioritize gait correctness over silhouette',()=>{const plan=buildPosePlan(run),details=createRepairPlanDetails({pose:plan.frames[4],issue:'leg_progression',description:'same side repeated',pairedFrame:plan.frames[0],neighbors:[3,5]});assert.ok(details.must_change.some(item=>/contralateral silhouette/i.test(item)));assert.match(details.must_not_change[0],/identity/i);});
test('semantic validator exposes confidence so weak findings can be down-weighted',async()=>{const result=await new ExternalManualVisionProvider().validate_animation({animation_id:'walk',max_frame_index:7,supervisor_result:{passed:false,score:60,confidence:.3,phase_accuracy:.4,phase_accuracy_confidence:.2,issues:[{type:'leg_progression',frame_index:4,severity:'high',description:'uncertain lead leg'}],bad_frames:[4]}});assert.equal(result.confidence_label,'low');assert.equal(result.phase_accuracy_confidence,.2);});
