import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import {mkdtemp,rm} from 'node:fs/promises';
import {PROCESS_STATES,createSupervisorSession,observeRepairSession,deprioritizeLowPerformingStrategies} from '../automation/process-supervisor.mjs';
import {ExperienceService} from '../automation/experience-service.mjs';

const validation=(score,issues=[])=>({score,passed:false,issues:issues.map((type,index)=>({type,severity:type==='anatomy'?'high':'medium',frame_index:index}))});
const baseRun=({score=80,issues=['leg_progression'],strictness='balanced'}={})=>{const run={id:'walk-1',animation_type:'WALKING',frame_records:[{frame_id:'best-frame',frame_index:0,storage_path:'best.png'}],technical_validation:validation(score,issues),semantic_validation:null,combined_validation:null,repair_plans:[],supervisor_strictness:strictness};run.process_supervisor=createSupervisorSession(run,{strictness});return run;};
function attempt(run,{before,after,issues=['leg_progression'],strategy='frame_local',prompt=100,baseWasBestKnown=true}={}){const number=run.process_supervisor.observations.length+1;run.repair_plans.push({attempt:number,base_result:'BEST_KNOWN_RESULT',base_result_score:run.process_supervisor.best_known_result.score,previous_validation_score:before,validator_scores_before:{technical:before},issue_types_before:issues,frames_to_repair:[{frame_index:0,phase:'passing',strategy_id:strategy,repair_action:strategy}],repair_results:[{instruction_summary:'x'.repeat(prompt)}]});run.technical_validation=validation(after,issues);run.frame_records=[{frame_id:`attempt-${number}`,frame_index:0,storage_path:`attempt-${number}.png`}];run.process_supervisor=observeRepairSession(run,{technical:run.technical_validation,promptComplexity:prompt,baseWasBestKnown});return run.process_supervisor;}

test('three non-improving retries trigger PROCESS_FAILURE and halt',()=>{const run=baseRun();attempt(run,{before:80,after:81});attempt(run,{before:81,after:82});const result=attempt(run,{before:82,after:83});assert.equal(result.state,PROCESS_STATES.HALTED);assert.equal(result.halted,true);assert.ok(result.triggers.includes('consecutive_non_improving_retries'));});

test('two BEST_KNOWN_RESULT regressions halt and preserve the best snapshot',()=>{const run=baseRun();attempt(run,{before:80,after:70,issues:['leg_progression','anatomy']});const result=attempt(run,{before:80,after:60,issues:['leg_progression','anatomy']});assert.equal(result.halted,true);assert.ok(result.triggers.includes('consecutive_best_known_regressions'));assert.equal(result.best_known_result.score,80);assert.equal(result.best_known_result.frame_records[0].frame_id,'best-frame');});

test('a regressive attempt is rejected as a future repair base',()=>{const run=baseRun();const result=attempt(run,{before:80,after:70});assert.equal(result.state,PROCESS_STATES.WARNING);assert.equal(result.observations.at(-1).regressive,true);assert.equal(result.best_known_result.frame_records[0].frame_id,'best-frame');});

test('persistent issue across three distinct strategies produces diagnosis',()=>{const run=baseRun();attempt(run,{before:80,after:85,strategy:'one'});attempt(run,{before:85,after:90,strategy:'two'});const result=attempt(run,{before:90,after:95,strategy:'three'});assert.ok(result.triggers.includes('persistent_issue_across_attempts_or_strategies'));assert.deepEqual(result.diagnosis.persistent_issues,['leg_progression']);assert.equal(result.diagnosis.strategies_tried.length,3);});

test('oscillation between two failure states is detected',()=>{const run=baseRun({score:50,issues:['issue_a'],strictness:'aggressive'});attempt(run,{before:50,after:60,issues:['issue_a']});attempt(run,{before:60,after:70,issues:['issue_b']});attempt(run,{before:70,after:80,issues:['issue_a']});const result=attempt(run,{before:80,after:90,issues:['issue_b']});assert.ok(result.triggers.includes('oscillating_failure_states'));});
test('repeated paired-frame failure is surfaced by the supervisor',()=>{const run=baseRun();attempt(run,{before:80,after:81,issues:['incorrect_same_side_repetition']});const result=attempt(run,{before:81,after:82,issues:['incorrect_same_side_repetition']});assert.ok(result.triggers.includes('repeated_paired_frame_failure'));});

test('known low-performing strategy is deprioritized and repeated selection is detected',()=>{const ranking={repair_action:'bad',strategy_id:'bad',ranked_strategies:[{strategy_id:'bad',repair_action:'bad',confidence:'provisional',ranking_score:-20},{strategy_id:'good',repair_action:'good',confidence:'provisional',ranking_score:40}]},selected=deprioritizeLowPerformingStrategies(ranking,['bad']);assert.equal(selected.strategy_id,'good');const run=baseRun();const stats=[{strategy_id:'bad',attempts:4,ranking_score:-20,success_rate:0}];run.repair_plans.push({attempt:1,base_result:'BEST_KNOWN_RESULT',base_result_score:80,previous_validation_score:80,issue_types_before:['leg_progression'],frames_to_repair:[{frame_index:0,strategy_id:'bad'}]});run.process_supervisor=observeRepairSession(run,{technical:validation(85,['leg_progression']),strategyStats:stats});run.repair_plans.push({attempt:2,base_result:'BEST_KNOWN_RESULT',base_result_score:85,previous_validation_score:85,issue_types_before:['leg_progression'],frames_to_repair:[{frame_index:0,strategy_id:'bad'}]});const result=observeRepairSession({...run,technical_validation:validation(90,['leg_progression'])},{technical:validation(90,['leg_progression']),strategyStats:stats});assert.ok(result.triggers.includes('known_poor_strategy_reselected'));assert.ok(result.disabled_strategies.includes('bad'));});

test('recoverable identity regression produces only a bounded runtime correction',()=>{const run=baseRun();attempt(run,{before:80,after:70,issues:['leg_progression','anatomy']});const result=attempt(run,{before:80,after:69,issues:['leg_progression','anatomy']});assert.equal(result.state,PROCESS_STATES.HALTED);assert.equal(result.correction_request.bounded,true);assert.equal(result.correction_request.kind,'runtime_policy_adjustment');assert.equal(result.codex_escalation_prompt,null);});

test('implementation-level base anchoring failure produces a focused Codex prompt',()=>{const run=baseRun();const result=attempt(run,{before:80,after:81,baseWasBestKnown:false});assert.equal(result.state,PROCESS_STATES.ESCALATION_REQUIRED);assert.match(result.codex_escalation_prompt,/BEST_KNOWN_RESULT anchoring/);assert.match(result.codex_escalation_prompt,/Do not redesign providers, UI, deployment/);});

test('process failure events persist across restart',async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'sprited-supervisor-'));t.after(()=>rm(root,{recursive:true,force:true}));const options={experiencePath:path.join(root,'experience.json'),timingPath:path.join(root,'timing.json')},service=await new ExperienceService(options).init();await service.record_supervisor_event({animation_id:'walk-1',animation_type:'WALKING',failure_trigger:['oscillating_failure_states'],diagnosis:{likely_process_cause:'repair scope too broad'},action_chosen:'bounded_runtime_correction',strategy_config_change:{repair_scope:'frame_local'},before_result:{score:60},after_result:{score:80}});const restarted=await new ExperienceService(options).init();assert.equal(restarted.experiences.supervisor_events.length,1);assert.equal(restarted.experiences.supervisor_events[0].failure_trigger[0],'oscillating_failure_states');});

test('halted and regressive attempts never become positive learning evidence',async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'sprited-supervisor-learning-'));t.after(()=>rm(root,{recursive:true,force:true}));const service=await new ExperienceService({experiencePath:path.join(root,'experience.json'),timingPath:path.join(root,'timing.json')}).init(),record=await service.record_experience({attempt_id:'halted',animation_type:'WALKING',issue_type:'leg_progression',strategy_id:'bad',repair_action:'bad',validator_scores_before:{overall:80},validator_scores_after:{overall:90},repair_succeeded:true,supervisor_halted:true,learning_eligible:false});assert.equal(record.repair_succeeded,false);assert.equal(record.learning_eligible,false);assert.equal(service.experiences.strategy_stats[0].successes,0);});
