import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import {mkdtemp,rm} from 'node:fs/promises';
import {ExperienceService} from '../automation/experience-service.mjs';
import {assessAnimationQuality} from '../automation/repair-orchestrator.mjs';
import {prepareAssistedRequest} from '../automation/chatgpt-assisted.mjs';
import {createSupervisorSession,observeRepairSession,PROCESS_STATES} from '../automation/process-supervisor.mjs';

const candidate={animation_type:'WALKING',issue_type:'wrong_lead_trail_leg',frame_phase:'right contact',affected_frames:[4],context_tags:['contralateral_pair_failure','silhouette_over_preserved'],rejection_reason:'Frame 5 still matches Frame 1 too closely',validator_scores:{overall:88},target_issue_scores:{lead_trail:20},paired_frame_relation:{paired_frame_index:0},loop_quality:{failure_type:'frame_8_to_1_jump'},strategy_id:'generic_retry'};
const run={id:'walk',animation_type:'WALKING',options:{quality_mode:'fast',loop:true},recipe_snapshot:{loop:true},frame_records:[],technical_validation:{score:95,passed:true,loop_validation:{passed:true,loop_score:95},issues:[]},semantic_validation:{passed:true,semantic_score:95,issues:[]},repair_plans:[]};

test('rejected result creates memory and semantic repeat matches',async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'sprited-rejected-'));t.after(()=>rm(root,{recursive:true,force:true}));const service=await new ExperienceService({experiencePath:path.join(root,'experience.json'),timingPath:path.join(root,'timing.json')}).init();const first=await service.record_rejected_pattern(candidate),matches=service.find_rejected_patterns({...candidate,issue_type:'contralateral_pair_failure',rejection_reason:'opposite contact pose remains too close'});assert.equal(first.times_rejected,1);assert.ok(matches[0].similarity>=.62);const reloaded=await new ExperienceService({experiencePath:path.join(root,'experience.json'),timingPath:path.join(root,'timing.json')}).init();assert.equal(reloaded.experiences.rejected_patterns.length,1);});
test('repeated failure overrides GOOD_ENOUGH and preserves approval gate',()=>{const quality=assessAnimationQuality(run,{qualityMode:'fast',rejectedPatterns:[{...candidate,similarity:.9}]});assert.equal(quality.quality_state, 'REPEATED_FAILURE');assert.equal(quality.next_action,'regenerate_bad_frames');});
test('repair prompt includes negative rejected-pattern guidance',()=>{const request=prepareAssistedRequest({run:{...run,options:{...run.options,output_frames:8,canvas_width:256,canvas_height:256},frame_records:Array.from({length:8},(_,frame_index)=>({frame_index,frame_id:`f${frame_index}`}))},frameIndex:4,rejectedPatterns:[{...candidate,similarity:.9}]});assert.match(request.prompt,/Avoid known rejected pattern/i);assert.match(request.prompt,/Frame 5 still matches Frame 1/i);});
test('process supervisor reacts to repeated rejected pattern',()=>{const base={...run,process_supervisor:createSupervisorSession({...run,technical_validation:{score:80,issues:[{type:'wrong_lead_trail_leg'}]}})};base.repair_plans=[{attempt:1,base_result:'BEST_KNOWN_RESULT',base_result_score:80,previous_validation_score:80,issue_types_before:['wrong_lead_trail_leg'],frames_to_repair:[{frame_index:4,phase:'right contact',strategy_id:'generic_retry'}]}];const first=observeRepairSession(base,{technical:{score:82,issues:[{type:'wrong_lead_trail_leg',frame_index:4}]},rejectedPatternMatches:[{...candidate,times_seen:2}]});assert.ok(first.triggers.includes('repeated_rejected_pattern'));assert.equal(first.state,PROCESS_STATES.HALTED);});
test('human rejection is marked as strong negative evidence',async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'sprited-human-reject-'));t.after(()=>rm(root,{recursive:true,force:true}));const service=await new ExperienceService({experiencePath:path.join(root,'experience.json'),timingPath:path.join(root,'timing.json')}).init(),record=await service.record_rejected_pattern({...candidate,human_rejection:true,rejection_reason:'same mistake again'});assert.equal(record.human_rejection,true);assert.equal(record.rejection_reason,'same mistake again');});
