import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,stat,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {RetentionService,normalizeRetention} from '../automation/retention-service.mjs';
import {ExperienceService} from '../automation/experience-service.mjs';
import {Service} from '../automation/service.mjs';
import {getAnimationStatus} from '../automation/repair-orchestrator.mjs';
import '../public/character-workflow.js';

const exists=async file=>stat(file).then(()=>true,()=>false);
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'sprited-retention-'));await mkdir(path.join(root,'assets'));const put=async name=>{const file=path.join(root,'assets',name);await writeFile(file,name.endsWith('.png')?Buffer.from('89504e470d0a1a0a','hex'):Buffer.from(name));return {file,relative:path.relative(root,file)};};return {root,put};}
const artifact=(id,owner,role,file,output_path=null)=>({artifact_id:id,owner_animation_id:owner,role,storage_path:file,...(output_path?{output_path}:{}),pinned:false});

test('cleanup manifest keeps only final sheet and pinned artifacts by default',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const files={frame:await f.put('final-frame.png'),contact:await f.put('contact.png'),gif:await f.put('preview.gif'),sheet:await f.put('sheet.png'),meta:await f.put('sheet.json'),failed:await f.put('failed.png'),active:await f.put('active.png')},final={id:'final',character_profile_id:'c',animation_type:'WALKING',status:'approved',approval_state:'approved',user_approved:true,frame_records:[{frame_id:'frame-final',storage_path:files.frame.relative}],contact_sheets:[{contact_sheet_id:'contact',storage_path:files.contact.relative}],gif_previews:[{preview_id:'gif',storage_path:files.gif.relative}],spritesheets:[{id:'sheet',artifacts:[artifact('sheet-png','final','final_spritesheet',files.sheet.relative,files.sheet.file),artifact('sheet-meta','final','spritesheet_metadata',files.meta.relative,files.meta.file)]}]},rejected={id:'rejected',character_profile_id:'c',animation_type:'WALKING',status:'rejected',approval_state:'rejected',frame_records:[{frame_id:'failed-frame',storage_path:files.failed.relative}]},active={id:'active',character_profile_id:'c',animation_type:'WALKING',status:'generating',approval_state:'pending',frame_records:[{frame_id:'active-frame',storage_path:files.active.relative}]},manifest=new RetentionService().createCleanupManifest(final,[final,rejected,active],{pinned_artifact_ids:['contact']});const byId=new Map(manifest.entries.map(item=>[item.artifact_id,item]));assert.equal(byId.get('sheet-png').action,'retain');assert.equal(byId.get('contact').action,'retain');for(const id of ['frame-final','gif','sheet-meta','failed-frame'])assert.equal(byId.get(id).action,'delete');assert.equal(byId.has('active-frame'),false);});

test('known artifacts are unlinked individually while final and pinned files remain',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const doomed=await Promise.all(['failed-generation.png','failed-repair.png','obsolete.png','contact.png','preview.gif'].map(name=>f.put(name))),sheet=await f.put('approved.png'),pinned=await f.put('pinned.png'),manifest={cleanup_id:'cleanup',animation_id:'final',status:'pending',entries:[...doomed.map((item,index)=>artifact(['failed-generation','failed-repair','obsolete','contact','preview'][index],'final',['failed_generation_frame','failed_repair_frame','obsolete_replaced_frame','contact_sheet','preview_gif'][index],item.relative)),{...artifact('sheet','final','final_spritesheet',sheet.relative,sheet.file),action:'retain'},{...artifact('pinned','final','contact_sheet',pinned.relative,pinned.file),action:'retain'}].map(item=>item.action?item:{...item,action:'delete'})};let completed=false;const fake={root:f.root,contained(target){const resolved=path.resolve(target);assert.ok(resolved.startsWith(path.resolve(f.root)+path.sep));return resolved;},core:async(action)=>{assert.equal(action,'workflow/animation/complete-cleanup');completed=true;},persist:async()=>{},experienceService:{record_timing:async()=>{}}};await Service.prototype.executeCleanupManifest.call(fake,manifest);assert.equal(completed,true);for(const item of doomed)assert.equal(await exists(item.file),false);assert.equal(await exists(sheet.file),true);assert.equal(await exists(pinned.file),true);});

test('experience records and strategy ranking remain usable after image cleanup',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const service=await new ExperienceService({experiencePath:path.join(f.root,'experience.json'),timingPath:path.join(f.root,'timing.json')}).init(),image=await f.put('temporary.png');for(const succeeded of [true,true,false])await service.record_experience({animation_type:'WALKING',issue_type:'leg_progression',repair_action:succeeded?'regenerate_with_neighbors':'current_only',provider:'local_process',repair_succeeded:succeeded});await rm(image.file);const reloaded=await new ExperienceService({experiencePath:path.join(f.root,'experience.json'),timingPath:path.join(f.root,'timing.json')}).init(),ranking=reloaded.rank_repair_strategies({animation_type:'WALKING',issue_type:'leg_progression'},'regenerate');assert.equal(ranking.strategy_source,'experience');assert.equal(ranking.repair_action,'regenerate_with_neighbors');});

test('cleanup refuses missing export, incomplete validation, and failed experience persistence',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const png=await f.put('final.png'),base={id:'final',character_profile_id:'c',animation_type:'IDLE',status:'approved',approval_state:'approved',user_approved:true,validation:{warnings:[]},repair_plans:[],spritesheets:[{id:'sheet',artifacts:[artifact('sheet','final','final_spritesheet',png.relative,png.file)]}]},make=run=>({root:f.root,retentionService:new RetentionService(),core:async action=>action==='snapshot'?{workflow:{animation_runs:[run]}}:null,input:async()=>png.file,recordProgress:async()=>{},experienceService:{ensure_persisted:async()=>{throw Error('persist failed');}},persist:async()=>{},executeCleanupManifest:async()=>{throw Error('must not delete');}});await assert.rejects(()=>Service.prototype.cleanupFinalizedAnimation.call(make({...base,spritesheets:[]}),base.id),/SpriteSheet/);await assert.rejects(()=>Service.prototype.cleanupFinalizedAnimation.call(make({...base,validation:null}),base.id),/validation/);await assert.rejects(()=>Service.prototype.cleanupFinalizedAnimation.call(make(base),base.id),/persist failed/);assert.equal(await exists(png.file),true);});

test('active repair blocks cleanup',async()=>{const run={id:'final',character_profile_id:'c',animation_type:'ATTACK',status:'approved',approval_state:'approved',user_approved:true,validation:{},semantic_reinspection_required:false,repair_plans:[{status:'active'}],spritesheets:[]},fake={core:async action=>action==='snapshot'?{workflow:{animation_runs:[run]}}:null};await assert.rejects(()=>Service.prototype.cleanupFinalizedAnimation.call(fake,run.id),/active/);});

test('restart reconciliation resumes only pending ownership manifests',async()=>{const pending={id:'a',cleanup_pending:true,cleanup_manifest:{cleanup_id:'one',status:'pending'}},done={id:'b',cleanup_pending:false,cleanup_manifest:{cleanup_id:'two',status:'completed'}},seen=[],fake={core:async action=>{assert.equal(action,'snapshot');return {workflow:{animation_runs:[pending,done]}};},executeCleanupManifest:async manifest=>seen.push(manifest.cleanup_id)};await Service.prototype.reconcileCleanup.call(fake);assert.deepEqual(seen,['one']);});

test('a cleanup I/O failure remains pending instead of rolling back its manifest',async t=>{const f=await fixture();t.after(()=>rm(f.root,{recursive:true,force:true}));const png=await f.put('final.png'),run={id:'final',character_profile_id:'c',animation_type:'IDLE',status:'approved',approval_state:'approved',user_approved:true,validation:{},repair_plans:[],retention:normalizeRetention(),frame_records:[],spritesheets:[{id:'sheet',artifacts:[artifact('sheet','final','final_spritesheet',png.relative,png.file)]}]},calls=[],fake={root:f.root,retentionService:new RetentionService(),core:async(action,args)=>{calls.push(action);if(action==='snapshot')return {workflow:{animation_runs:[run]}};return args;},input:async()=>png.file,recordProgress:async()=>{},experienceService:{ensure_persisted:async()=>({record_count:0})},persist:async()=>{},executeCleanupManifest:async()=>{throw Error('file busy');}};const result=await Service.prototype.cleanupFinalizedAnimation.call(fake,run.id);assert.equal(result.cleanup_pending,true);assert.ok(calls.includes('workflow/animation/record-cleanup-plan'));});

test('retention implementation contains no recursive or directory deletion',async()=>{const source=await readFile(new URL('../automation/retention-service.mjs',import.meta.url),'utf8'),executor=Service.prototype.executeCleanupManifest.toString();assert.equal(source.includes('rm('),false);assert.equal(source.includes('rmdir'),false);assert.ok(executor.includes('unlink'));assert.equal(executor.includes('recursive'),false);assert.deepEqual(normalizeRetention(),{keep_final_spritesheet:true,keep_final_frames:false,keep_failed_frames:false,keep_contact_sheets:false,keep_preview_gifs:false,keep_experience_history:true,pinned_artifact_ids:[]});});

test('cleaned animation status remains finalized without offering frame operations',()=>{const status=getAnimationStatus({id:'a',animation_type:'IDLE',character_profile_id:'c',storage_state:'cleaned',sprite_sheet_path:'sheet.png',user_approved:true,frame_records:[],options:{loop:false},technical_validation:{passed:true,score:100,issues:[],loop_validation:{passed:true,loop_score:100}},semantic_validation:{passed:true,semantic_score:100,issues:[]},combined_validation:{overall_passed:true},repair_plans:[],temporary_artifact_count:0,retained_artifact_count:1,cleanup_pending:false});assert.equal(status.overall_status,'passed');assert.equal(status.storage_state,'cleaned');assert.equal(status.temporary_artifact_count,0);assert.equal(status.retained_artifact_count,1);assert.deepEqual(status.allowed_next_actions,[]);});

test('legacy sheet ownership is migrated without filename guessing',()=>{const workflow=globalThis.SpritedWorkflow,state=workflow.empty(),src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XyVZ5wAAAABJRU5ErkJggg==';workflow.setReference(state,{src,name:'Legacy'});const run=workflow.create(state,'IDLE');run.spritesheets=[{id:'old-sheet',output_paths:['one','two','three','four','five']}];state.animation_runs[0]=run;const restored=workflow.hydrate(state).animation_runs[0].spritesheets[0];assert.deepEqual(restored.artifacts.map(item=>item.role),['final_spritesheet','spritesheet_metadata','editable_project','export_manifest','frame_copy']);assert.ok(restored.artifacts.every(item=>item.owner_animation_id===run.id));});
