import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir,homedir} from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createInterface} from 'node:readline';
import {pathToFileURL} from 'node:url';

test('packaged MCP and internal controller share safe character content through the Cloudflare provider boundary',async()=>{
  const packageRoot=path.resolve(process.argv[2]||'outputs/SPRITED-0.12.0-dev-win'),log=path.join(process.env.LOCALAPPDATA||path.join(homedir(),'AppData','Local'),'SPRITED','library-server.log'),text=await readFile(log,'utf8'),line=text.split(/\r?\n/).filter(value=>value.startsWith('Library: ')).at(-1),libraryUrl=new URL(line.slice(9)),token=libraryUrl.hash.slice(1),api=libraryUrl.origin,child=spawn(path.join(packageRoot,'runtime','node.exe'),[path.join(packageRoot,'automation','cli.mjs'),'mcp','--api',api],{env:{...process.env,SPRITED_TOKEN:token},stdio:['pipe','pipe','pipe'],windowsHide:true});
  const pending=new Map();let sequence=0,stderr='';child.stderr.on('data',data=>stderr+=data);createInterface({input:child.stdout}).on('line',value=>{const message=JSON.parse(value);pending.get(message.id)?.(message);pending.delete(message.id);});const rpc=(method,params={})=>new Promise((resolve,reject)=>{const id=++sequence,timer=setTimeout(()=>reject(Error(stderr||'MCP timeout')),15000);pending.set(id,message=>{clearTimeout(timer);resolve(message);});child.stdin.write(JSON.stringify({jsonrpc:'2.0',id,method,params})+'\n');});let root,service;
  try{
    const identity=await fetch(api+'/identity',{headers:{authorization:`Bearer ${token}`}}).then(response=>response.json());assert.equal(path.resolve(identity.cli_path),path.join(packageRoot,'automation','cli.mjs'));
    await rpc('initialize',{clientInfo:{name:'runtime-content-boundary'}});const listed=await rpc('tools/call',{name:'list_characters',arguments:{}}),guardian=listed.result.structuredContent.result.find(character=>character.id==='6d735ff64a40a74dd81ffb15236f0dd5');assert.equal(guardian.name,'Guardian Smoke');const got=await rpc('tools/call',{name:'get_character',arguments:{id:guardian.id}});assert.equal(got.result.isError,false);assert.equal(got.result.content[1].type,'image');const publicResult=JSON.stringify(got.result.structuredContent);assert.equal(publicResult.includes('reference_image_path'),false);assert.equal(publicResult.includes('storage_path'),false);
    const traversal=await fetch(api+'/content/character/../../Windows/win.ini',{headers:{authorization:`Bearer ${token}`}});assert.notEqual(traversal.status,200);
    root=await mkdtemp(path.join(tmpdir(),'sprited-provider-boundary-'));await writeFile(path.join(root,'guardian.png'),Buffer.from(got.result.content[1].data,'base64'));const {Service}=await import(pathToFileURL(path.join(packageRoot,'automation','service.mjs')).href);service=await new Service(root).init();const localCharacter=(await service.call('character/create',{path:'guardian.png',name:'Guardian Boundary'})).result,provider=service.imageProviders.cloudflare_flux;let boundaryReached=false;provider.config.enabled=true;provider.environment={CLOUDFLARE_ACCOUNT_ID:'0123456789abcdef0123456789abcdef',CLOUDFLARE_API_TOKEN:'test-token'};provider.fetch=async(_url,options)=>{boundaryReached=true;assert.ok(options.body.get('input_image_0'));return {ok:false,status:418,headers:{get:()=> 'application/json'},json:async()=>({success:false})};};service.providerPolicy={default_provider:'cloudflare_flux',fallback_providers:[],allow_paid_providers:true,allow_automatic_paid_fallback:false,require_confirmation_for_paid_request:true,max_paid_image_generations_per_animation:2,max_paid_repair_generations_per_animation:1};const pipeline=await service.call('pipeline/run',{character_id:localCharacter.id,animation_type:'WALKING',frames:2,provider:'cloudflare_flux',repair_intelligence:'sprited_only',confirm_paid_request:true});assert.equal(boundaryReached,true);assert.equal(pipeline.status,'failed');assert.match(pipeline.result.errors[0],/Cloudflare FLUX request failed \(418\)/);assert.equal(JSON.stringify(pipeline).includes('readContentReference is not a function'),false);assert.equal(JSON.stringify(pipeline).includes('test-token'),false);
  }finally{child.stdin.end();await new Promise(resolve=>child.once('exit',resolve));await service?.close();if(root)await rm(root,{recursive:true,force:true});}
});
