import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';

const address=process.argv[2],screenshot=path.resolve(process.argv[3]||'test-results/SPRITED-0.12.0-dev.png'),runtimeRoot=path.resolve(process.argv[4]||'.');
assert.ok(address?.startsWith('http://127.0.0.1:'));
const parsed=new URL(address),token=parsed.hash.slice(1),headers={authorization:`Bearer ${token}`},png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XyVZ5wAAAABJRU5ErkJggg==','base64');
let characters=await fetch(new URL('/character/list',parsed.origin),{headers}).then(response=>response.json());
if(!characters.result.length)await fetch(new URL('/ui/reference?name=Prompt%20Guardian',parsed.origin),{method:'POST',headers:{...headers,'content-type':'image/png'},body:png});
const temp=await mkdtemp(path.join(tmpdir(),'sprited-ui-')),frame1=path.join(temp,'frame-01.png'),frame2=path.join(temp,'frame-02.png'),sheetFile=path.join(temp,'source-sheet.png');await writeFile(frame1,png);await writeFile(frame2,png);
const require=createRequire(import.meta.url),playwright=require(path.join(runtimeRoot,'automation','node_modules','playwright-core')),browser=await playwright.chromium.launch({channel:'msedge',headless:true});
try{
  const page=await browser.newPage({viewport:{width:1500,height:980}});await page.goto(address);await page.waitForSelector('#generatePrompt:not([disabled])');const generated=await page.evaluate(()=>{const frames=[90,150].map(value=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=64;const context=canvas.getContext('2d');context.fillStyle=`rgb(${value} ${value} ${value})`;context.fillRect(18,8,28,48);return canvas;});const sheet=document.createElement('canvas');sheet.width=128;sheet.height=64;const context=sheet.getContext('2d');context.drawImage(frames[0],0,0);context.drawImage(frames[1],64,0);return {frames:frames.map(canvas=>canvas.toDataURL('image/png').split(',')[1]),sheet:sheet.toDataURL('image/png').split(',')[1]};});await writeFile(frame1,Buffer.from(generated.frames[0],'base64'));await writeFile(frame2,Buffer.from(generated.frames[1],'base64'));await writeFile(sheetFile,Buffer.from(generated.sheet,'base64'));
  for(const id of ['generatePrompt','promptOutput','chooseFrames','buildSheet','updatesOpen','advancedOpen'])assert.equal(await page.locator('#'+id).count(),1,id);
  const normal=await page.locator('body').innerText();for(const hidden of ['Connect Codex','Connect Cline','Cloudflare','Gemini','OpenAI API','API key'])assert.equal(normal.includes(hidden),false,hidden);assert.equal(normal.includes(token),false);
  await page.locator('#promptMode').selectOption('full_gait');await page.locator('#generatePrompt').click();await page.waitForFunction(()=>document.querySelector('#promptOutput').value.length>100);assert.match(await page.locator('#promptOutput').inputValue(),/1\. left contact/i);assert.match(await page.locator('#promptOutput').inputValue(),/8\. right up/i);
  await page.locator('#sliceColumns').fill('2');await page.locator('#sliceRows').fill('1');await page.locator('#sheetFile').setInputFiles(sheetFile);await page.waitForFunction(()=>document.querySelectorAll('#frameList article').length===2);assert.match(await page.locator('#sheetStatus').textContent(),/left-to-right/);await page.locator('#sheetWidth').fill('32');await page.locator('#sheetHeight').fill('32');await page.locator('#sheetColumns').fill('2');await page.locator('#sheetSpacing').fill('2');await page.locator('#buildSheet').click();try{await page.waitForFunction(()=>!document.querySelector('#exportSheet').disabled,undefined,{timeout:60000});}catch{throw Error(await page.locator('#sheetStatus').textContent());}
  assert.equal(await page.locator('#qualityResult').isVisible(),true);const dimensions=await page.locator('#sheetPreview').evaluate(image=>[image.naturalWidth,image.naturalHeight]);assert.deepEqual(dimensions,[66,32]);await page.locator('#updatesOpen').click();await page.waitForFunction(()=>document.querySelector('#updatesDrawer').classList.contains('open')&&document.querySelector('#learningEvents').textContent.trim().length>0);assert.match(await page.locator('#learningEvents').innerText(),/Prompt|SpriteSheet|Frame|NEEDS_REPAIR|GOOD_ENOUGH|EXCELLENT/i);await page.screenshot({path:screenshot,fullPage:true});
  await page.reload();await page.waitForSelector('#attemptHistory',{state:'attached'});await page.waitForFunction(()=>document.querySelectorAll('#attemptHistory option').length>1);assert.ok(await page.locator('#attemptHistory option').count()>1);console.log(`PASS: prompt, PNG import/order, ${dimensions[0]}x${dimensions[1]} SpriteSheet, updates drawer and restart persistence. Screenshot: ${screenshot}`);
}finally{await browser.close();await rm(temp,{recursive:true,force:true});}
