import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile,stat,utimes} from 'node:fs/promises';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {createServer} from 'node:http';
import path from 'node:path';
import {acquireLock,releaseLock,inspectProcess} from '../automation/lock.mjs';
async function exec(command,args,options={}){if(command!=='powershell.exe')return promisify(execFile)(command,args,options);return new Promise((resolve,reject)=>{const child=spawn(command,args,{...options,stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);const timer=setTimeout(()=>{child.kill();reject(Error('Launcher process timed out'));},options.timeout||100000);child.once('error',reject);child.once('exit',code=>{clearTimeout(timer);child.stdout.destroy();child.stderr.destroy();if(code===0)resolve({stdout,stderr});else reject(Error('Launcher exit '+code+': '+stderr));});});}
const base=path.resolve(process.env.SPRITED_STARTUP_TEST_ROOT||'../startup-tests');await mkdir(base,{recursive:true});
const script=path.resolve(process.env.SPRITED_STARTUP_SCRIPT||'automation/Open-Library.ps1');const children=[];const servers=[];
async function workspace(name){const root=path.join(base,name);await mkdir(path.join(root,'.sprited'),{recursive:true});await writeFile(path.join(root,'library-data-marker.txt'),'DO NOT DELETE');return root;}
async function launch(root){const r=await exec('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script,'-DataDirectory',root,'-NoOpen'],{windowsHide:true,timeout:100000,env:process.env});assert.match(r.stdout,/SPRITED_STARTUP_OK/);const line=(await readFile(path.join(root,'library-server.log'),'utf8')).split(/\r?\n/).filter(l=>l.startsWith('Library: ')).at(-1);assert.ok(line);const url=new URL(line.slice(9)),headers={authorization:'Bearer '+url.hash.slice(1)};const identity=await fetch(url.origin+'/identity',{headers}).then(r=>r.json());if(identity.application==='SPRITED')children.push(identity.pid);assert.equal(await readFile(path.join(root,'library-data-marker.txt'),'utf8'),'DO NOT DELETE');assert.equal((await fetch(url.origin+'/ui/')).status,200);return {url,headers,identity,output:r.stdout};}
async function stop(pid){try{process.kill(pid);}catch{}for(let i=0;i<50;i++){if(!(await inspectProcess(pid)).exists)return;await new Promise(r=>setTimeout(r,100));}}
try{
 const clean=await workspace('clean');let live=await launch(clean);assert.equal(live.identity.application,'SPRITED');const again=await launch(clean);assert.equal(again.identity.pid,live.identity.pid);assert.match(again.output,/reconnected/);await stop(live.identity.pid);console.log('PASS clean startup, exact live identity/reconnect; force-exit fixture');
 // Simulates the real crash: the freshly written structured lock survives a force exit.
 const recovered=await launch(clean);assert.notEqual(recovered.identity.pid,live.identity.pid);assert.match(await readFile(path.join(clean,'startup.log'),'utf8'),/stale-lock-removed/);await stop(recovered.identity.pid);console.log('PASS crashed server structured PID/lock recovery; data preserved');
 const stale=await workspace('stale-lock-only');await writeFile(path.join(stale,'.sprited/automation.lock'),'2147483000');live=await launch(stale);await stop(live.identity.pid);console.log('PASS legacy stale PID lock without server marker');
 const unrelated=spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{windowsHide:true});children.push(unrelated.pid);
 const occupied=await workspace('unrelated-port');await writeFile(path.join(occupied,'.sprited/automation.lock'),String(unrelated.pid));await utimes(path.join(occupied,'.sprited/automation.lock'),new Date(0),new Date(0));const other=createServer((req,res)=>{res.writeHead(403);res.end('not SPRITED');});await new Promise(r=>other.listen(0,'127.0.0.1',r));servers.push(other);await writeFile(path.join(occupied,'library-server.log'),`Library: http://127.0.0.1:${other.address().port}/ui/#stale-token\n`);live=await launch(occupied);assert.notEqual(Number(live.url.port),other.address().port);assert.equal((await inspectProcess(unrelated.pid)).exists,true);assert.match(await readFile(path.join(occupied,'startup.log'),'utf8'),/port-inspected/);await stop(live.identity.pid);console.log('PASS unrelated node PID and occupied unrelated port: no process killed, free port chosen');
 const malformed=await workspace('malformed-lock');const lock=path.join(malformed,'.sprited/automation.lock');await writeFile(lock,'');await utimes(lock,new Date(0),new Date(0));live=await launch(malformed);await stop(live.identity.pid);console.log('PASS abandoned empty lock recovery');
 const concurrent=await workspace('concurrent');const lockPath=path.join(concurrent,'.sprited/automation.lock');await writeFile(lockPath,'2147483000');const results=await Promise.allSettled([acquireLock(lockPath,concurrent),acquireLock(lockPath,concurrent)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);await releaseLock(lockPath,results.find(r=>r.status==='fulfilled').value);console.log('PASS simultaneous stale recovery: single lock owner');
 if(process.env.SPRITED_OLD_CLI){const oldRoot=await workspace('real-old-server');const probe=createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));const old=spawn(process.execPath,[path.resolve(process.env.SPRITED_OLD_CLI),'serve','--port',String(port),'--workspace',oldRoot],{windowsHide:true,env:process.env});children.push(old.pid);let output='';old.stdout.on('data',b=>{output+=b;});let errors='';old.stderr.on('data',b=>errors+=b);for(let i=0;i<180&&!output.includes('Library:');i++)await new Promise(r=>setTimeout(r,250));assert.match(output,/Library:/,errors+output);await writeFile(path.join(oldRoot,'library-server.log'),output);const r=await exec('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script,'-DataDirectory',oldRoot,'-NoOpen'],{windowsHide:true,timeout:100000});assert.match(r.stdout,/reconnected/);assert.equal((await inspectProcess(old.pid)).exists,true);assert.equal(await readFile(path.join(oldRoot,'library-data-marker.txt'),'utf8'),'DO NOT DELETE');await stop(old.pid);console.log('PASS real preview.3 server from different release: verified and reconnected without Windows restart');}
 console.log('PASS startup acceptance; UI endpoint reachable, library data preserved, logs include PID/executable/port/lock/cleanup. No user workspace touched.');
}finally{for(const pid of new Set(children))await stop(pid);for(const server of servers)await new Promise(r=>server.close(r));}
