import test from 'node:test';
import assert from 'node:assert/strict';
import {inspectPlayback,acceptedTransitions,temporalRegressions} from '../automation/temporal-inspector.mjs';

const frames=Array.from({length:8},(_,frame_index)=>({frame_index}));
const frameObservations=(loop=true)=>Object.fromEntries(frames.map(frame=>[frame.frame_index,{frame_index:frame.frame_index,timeline_position:frame.frame_index/(loop?8:7),body_center:{x:frame.frame_index,y:0},major_limb_positions:{phase:frame.frame_index},pose_confidence:.95,observation_confidence:.95}]));
const transitions=(loop=true)=>Array.from({length:loop?8:7},(_,index)=>({source_frame:index,target_frame:(index+1)%8,timeline_interval:[index/(loop?8:7),index===7?1:(index+1)/(loop?8:7)],expected_timeline_direction:'forward',continuity_confidence:.95,duplicate_near_duplicate_likelihood:0,reversal_likelihood:0,skipped_motion_likelihood:0,loop_seam_discontinuity:0,observation_confidence:.95}));

test('playback inspector evaluates every transition including mandatory loop closure',()=>{const result=inspectPlayback(frames,{loop:true,motionObservations:frameObservations(),transitionObservations:transitions()});assert.equal(result.transition_map.length,8);assert.deepEqual(result.transition_map.map(item=>[item.from_frame,item.to_frame]),[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,0]]);assert.equal(result.transition_map.at(-1).status,'PASS');assert.equal(result.passed,true);});
test('missing motion observations never produce optimistic approval',()=>{const result=inspectPlayback(frames,{loop:true});assert.equal(result.status,'INSUFFICIENT_MOTION_OBSERVATION');assert.equal(result.motion_approved,false);assert.equal(result.observation_coverage.observed,0);assert.ok(result.transition_map.every(item=>item.status==='INSUFFICIENT_OBSERVATION'));});
test('abrupt and frozen transitions map to responsible frames',()=>{const observed=transitions();observed[3].detected_issues=['abrupt_lead_leg_swap'];observed[3].responsible_frame=4;observed[4].detected_issues=['frozen_motion'];const result=inspectPlayback(frames,{loop:true,motionObservations:frameObservations(),transitionObservations:observed});assert.equal(result.transition_map[3].status,'FAIL');assert.equal(result.transition_map[3].responsible_frames[0],4);assert.ok(result.transition_map[4].detected_issues.includes('frozen_motion'));});
test('good transitions can lock and later regress',()=>{const observations=frameObservations(false),good=inspectPlayback(frames,{loop:false,motionObservations:observations,transitionObservations:transitions(false)}),locks=acceptedTransitions(good),badTransitions=transitions(false);badTransitions[1].detected_issues=['pelvis_discontinuity'];const bad=inspectPlayback(frames,{loop:false,motionObservations:observations,transitionObservations:badTransitions});assert.ok(locks.length>0);assert.ok(temporalRegressions(locks,bad).some(item=>item.from_frame===1));});
