import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createActionMotionSpec,createMotionTimeline,buildVirtualMotion,sampleVirtualMotion,validateVirtualMotion,createSamplingPlan} from '../automation/motion-engine.mjs';
import {WALKING_ACTION_MOTION_SPEC,WALKING_PHASE_SPECS,WALKING_VIRTUAL_MOTION,buildPosePlan} from '../automation/pose-planner.mjs';
import {buildMotionGenerationContext} from '../automation/service.mjs';

const attackSpec=()=>createActionMotionSpec({
  action_type:'ATTACK',cyclic:false,start_state:'ready',end_state:'recovery',direction_of_movement:'forward',
  key_poses:[
    {id:'ready',name:'Ready',timeline_position:0,is_anchor:true,virtual_motion_state:{body_center:{x:0,y:0},weapon_tool_trajectory:'guard',anticipation_amount:0,motion_direction:'forward'}},
    {id:'anticipation',name:'Anticipation',timeline_position:.18,virtual_motion_state:{body_center:{x:.03,y:0},weapon_tool_trajectory:'draw back',anticipation_amount:1,motion_direction:'forward'}},
    {id:'wind-up',name:'Wind-up',timeline_position:.38,virtual_motion_state:{body_center:{x:.08,y:0},weapon_tool_trajectory:'maximum wind-up',anticipation_amount:1,motion_direction:'forward'}},
    {id:'acceleration',name:'Acceleration',timeline_position:.55,virtual_motion_state:{body_center:{x:.2,y:0},weapon_tool_trajectory:'forward arc begins',anticipation_amount:.2,motion_direction:'forward'}},
    {id:'impact',name:'Impact',timeline_position:.65,is_anchor:true,virtual_motion_state:{body_center:{x:1,y:0},weapon_tool_trajectory:'impact',follow_through_amount:0,motion_direction:'forward'}},
    {id:'follow-through',name:'Follow-through',timeline_position:.8,virtual_motion_state:{body_center:{x:1.3,y:0},weapon_tool_trajectory:'forward arc completes',follow_through_amount:1,motion_direction:'forward'}},
    {id:'recovery',name:'Recovery',timeline_position:1,is_anchor:true,virtual_motion_state:{body_center:{x:1.4,y:0},weapon_tool_trajectory:'returns to guard',recovery_amount:1,motion_direction:'forward'}}
  ],
  motion_events:[{id:'anticipation-event',name:'Anticipation begins',type:'anticipation',timeline_position:.18},{id:'impact-event',name:'Impact',type:'impact',timeline_position:.65}],
  motion_segments:[
    ['ready','anticipation',0,.18,'ease-in'],['anticipation','wind-up',.18,.38,'constant'],['wind-up','acceleration',.38,.55,'ease-in'],['acceleration','impact',.55,.65,'ease-in'],['impact','follow-through',.65,.8,'ease-out'],['follow-through','recovery',.8,1,'ease-out']
  ].map(([source_motion_state,target_motion_state,start,end,easing])=>({id:`${source_motion_state}->${target_motion_state}`,source_motion_state,target_motion_state,timeline_range:[start,end],expected_trajectory:{motion_direction:'forward'},velocity_intent:easing==='constant'?'constant':easing,acceleration_intent:easing,easing,repair_range:[start,end]})),
  important_anchor_pose_ids:['ready','impact','recovery'],required_event_order:['anticipation-event','impact-event'],sampling_intent:{mode:'uniform'},action_specific_mechanics:{weapon_trajectory:'guard → wind-up → impact → recovery'}
});

const timingSpec=()=>createActionMotionSpec({action_type:'TIMING_TEST',cyclic:false,start_state:'start',end_state:'end',key_poses:[{id:'start',name:'Start',timeline_position:0,is_anchor:true,virtual_motion_state:{body_center:{x:0,y:0}}},{id:'impact',name:'Impact',timeline_position:.5,is_anchor:true,virtual_motion_state:{body_center:{x:1,y:0}}},{id:'end',name:'End',timeline_position:1,is_anchor:true,virtual_motion_state:{body_center:{x:2,y:0}}}],motion_segments:[{id:'accelerate',source_motion_state:'start',target_motion_state:'impact',timeline_range:[0,.5],easing:'ease-in',velocity_intent:'accelerating',acceleration_intent:'accelerating'},{id:'recover',source_motion_state:'impact',target_motion_state:'end',timeline_range:[.5,1],easing:'ease-out',velocity_intent:'decelerating',acceleration_intent:'decelerating'}],important_anchor_pose_ids:['start','impact','end'],sampling_intent:{mode:'uniform'}});

test('VirtualMotion constructs the complete action before frame sampling',()=>{const spec=attackSpec(),timeline=createMotionTimeline(spec),motion=buildVirtualMotion(spec,{timeline});assert.equal(motion.schema,'virtual-motion/v1');assert.equal(motion.action_motion_spec,spec);assert.equal(motion.motion_timeline,timeline);assert.equal(motion.preview_states[0].current_phase,'Ready');assert.equal(motion.preview_states.at(-1).current_phase,'Recovery');assert.equal('frame_count' in motion,false);assert.equal('samples' in motion,false);assert.equal(validateVirtualMotion(motion).passed,true);});

test('sampleVirtualMotion resolves arbitrary normalized time and authoritative key poses',()=>{const motion=buildVirtualMotion(attackSpec()),between=sampleVirtualMotion(motion,.6),impact=sampleVirtualMotion(motion,.65);assert.equal(between.motion_segment_id,'acceleration->impact');assert.ok(between.segment_progress>.4&&between.segment_progress<.6);assert.equal(between.surrounding_key_poses.previous.id,'acceleration');assert.equal(between.surrounding_key_poses.next.id,'impact');assert.equal(impact.key_pose_id,'impact');assert.deepEqual(impact.body_center,{x:1,y:0});assert.equal(impact.active_motion_events[0].id,'impact-event');});

test('equal-time samples allow accelerating displacement and decelerating recovery',()=>{const motion=buildVirtualMotion(timingSpec()),plan=createSamplingPlan(motion,{frameCount:9,mode:'uniform'}),positions=plan.samples.map(sample=>sample.timeline_position),x=plan.samples.map(sample=>sample.virtual_motion_state.body_center.x),steps=x.slice(1).map((value,index)=>value-x[index]);assert.deepEqual(positions,[0,.125,.25,.375,.5,.625,.75,.875,1]);assert.ok(steps[0]<steps[1]&&steps[1]<steps[2]&&steps[2]<steps[3]);assert.ok(steps[4]>steps[5]&&steps[5]>steps[6]&&steps[6]>steps[7]);assert.ok(plan.samples[1].virtual_motion_state.expected_velocity.normalized_speed<plan.samples[3].virtual_motion_state.expected_velocity.normalized_speed);assert.ok(plan.samples[5].virtual_motion_state.expected_velocity.normalized_speed>plan.samples[7].virtual_motion_state.expected_velocity.normalized_speed);});

test('cyclic VirtualMotion wraps t=1 to the start without a duplicate rendered sample',()=>{const wrapped=sampleVirtualMotion(WALKING_VIRTUAL_MOTION,1),plan=createSamplingPlan(WALKING_VIRTUAL_MOTION,{frameCount:8,mode:'uniform'});assert.equal(wrapped.loop_wrapped,true);assert.equal(wrapped.key_pose_id,'left-contact');assert.deepEqual(plan.samples.map(sample=>sample.timeline_position),[0,.125,.25,.375,.5,.625,.75,.875]);assert.equal(plan.samples.some(sample=>sample.timeline_position===1),false);});

test('anchor-preserving sampling retains an off-grid impact key pose',()=>{const motion=buildVirtualMotion(attackSpec()),uniform=createSamplingPlan(motion,{frameCount:8,mode:'uniform'}),anchored=createSamplingPlan(motion,{frameCount:8,mode:'anchor-preserving'});assert.equal(uniform.samples.some(sample=>sample.timeline_position===.65),false);assert.equal(anchored.samples.some(sample=>sample.key_pose_id==='impact'&&sample.timeline_position===.65),true);assert.equal(validateVirtualMotion(motion,{samplingPlan:anchored}).passed,true);});

test('8-frame and 12-frame ATTACK plans sample the same VirtualMotion',()=>{const spec=attackSpec(),motion=buildVirtualMotion(spec),eight=createSamplingPlan(motion,{frameCount:8}),twelve=createSamplingPlan(motion,{frameCount:12});assert.equal(eight.frame_count,8);assert.equal(twelve.frame_count,12);assert.equal(motion.action_motion_spec,spec);assert.deepEqual(eight.samples.map(item=>item.timeline_position),Array.from({length:8},(_,index)=>index/7));assert.deepEqual(twelve.samples.map(item=>item.timeline_position),Array.from({length:12},(_,index)=>index/11));assert.deepEqual(spec.action_specific_mechanics,{weapon_trajectory:'guard → wind-up → impact → recovery'});});

test('pre-generation validation rejects malformed planned motion',()=>{const valid=buildVirtualMotion(attackSpec());for(const [mutate,issue] of [[motion=>{motion.action_motion_spec.key_poses[2].timeline_position=.1;},'invalid_timeline_order'],[motion=>{motion.action_motion_spec.important_anchor_pose_ids.push('missing-anchor');},'missing_required_anchor'],[motion=>{motion.action_motion_spec.required_event_order=['impact-event','anticipation-event'];},'invalid_event_order'],[motion=>{motion.action_motion_spec.motion_events[1].id='anticipation-event';},'duplicated_important_event'],[motion=>{motion.action_motion_spec.motion_segments[1].source_motion_state='ready';},'segment_discontinuity']]){const broken=structuredClone(valid);mutate(broken);const result=validateVirtualMotion(broken);assert.equal(result.passed,false);assert.ok(result.issues.some(item=>item.type===issue),JSON.stringify(result));assert.throws(()=>createSamplingPlan(broken,{frameCount:8}),/INVALID_VIRTUAL_MOTION/);}});

test('pre-generation validation rejects a broken cyclic seam',()=>{const broken=structuredClone(WALKING_VIRTUAL_MOTION);broken.action_motion_spec.loop_seam.target='right-contact';const result=validateVirtualMotion(broken);assert.equal(result.passed,false);assert.ok(result.issues.some(item=>item.type==='broken_cyclic_seam'));});

test('WALKING uses generic VirtualMotion and preserves frame/export indices',async()=>{const run={animation_type:'WALKING',options:{output_frames:8,loop:true},recipe_snapshot:{loop:true,default_output_frame_count:8,motion_template:{phases:WALKING_PHASE_SPECS.map(item=>item.phase_name)}}},plan=buildPosePlan(run),source=await readFile(new URL('../automation/motion-engine.mjs',import.meta.url),'utf8');assert.equal(plan.virtual_motion,WALKING_VIRTUAL_MOTION);assert.equal(plan.virtual_motion_validation.passed,true);assert.deepEqual(plan.frames.map(frame=>frame.frame_index),[0,1,2,3,4,5,6,7]);assert.deepEqual(plan.frames.map(frame=>frame.virtual_motion_state.key_pose_id),['left-contact','left-down','left-passing','left-up','right-contact','right-down','right-passing','right-up']);assert.equal(WALKING_ACTION_MOTION_SPEC.action_specific_mechanics.kind,'walking-gait');assert.doesNotMatch(source,/WalkEngine|AttackEngine|WALKING_PHASE_SPECS/);});

test('generation context exposes intended VirtualMotionState without changing provider APIs',()=>{const run={animation_type:'WALKING',options:{output_frames:8,loop:true},recipe_snapshot:{loop:true,default_output_frame_count:8}},plan=buildPosePlan(run),records=plan.frames.map(frame=>({frame_index:frame.frame_index,frame_id:`f${frame.frame_index}`})),context=buildMotionGenerationContext({...run,pose_plan:plan},records,1).motionContext;assert.equal(context.target_timeline_position,.125);assert.equal(context.target_virtual_motion_state.key_pose_id,'left-down');assert.equal(context.surrounding_virtual_motion_states.previous.key_pose_id,'left-contact');assert.equal(context.surrounding_virtual_motion_states.next.key_pose_id,'left-passing');assert.equal(context.motion_segment.id,'left-down->left-passing');assert.equal(context.motion_direction,'forward');assert.equal(context.active_motion_events.length,0);});
