import {appendFile,readFile} from 'node:fs/promises';

const allowedTypes=new Set(['attempt_created','prompt_prepared','frame_imported','frame_replaced','validation_completed','loop_validation_completed','bad_frame_detected','quality_decision','repair_planned','repair_attempted','repair_succeeded','repair_failed','strategy_selected','strategy_score_changed','experience_recorded','confidence_changed','causal_lesson_distilled','regression_recorded','animation_approved','gif_exported','spritesheet_exported','plugin_connected','plugin_disconnected']);
const text=(value,max=240)=>typeof value==='string'&&value.trim()?value.trim().slice(0,max):null;
const score=value=>Number.isFinite(value)?Math.max(0,Math.min(100,Number(value))):null;

export class ActivityService {
  constructor({logPath,experienceService=null,now=()=>new Date().toISOString()}){this.logPath=logPath;this.experienceService=experienceService;this.now=now;this.events=[];}
  async init(){try{const lines=(await readFile(this.logPath,'utf8')).split(/\r?\n/).filter(Boolean);this.events=lines.slice(-2000).map(line=>JSON.parse(line)).filter(event=>allowedTypes.has(event.event_type));}catch(error){if(error.code!=='ENOENT')throw Error('Invalid SPRITED activity history');}return this;}
  async record(value){if(!allowedTypes.has(value.event_type))throw Error('Unsupported activity event');const event={timestamp:value.timestamp||this.now(),event_type:value.event_type,animation_type:text(value.animation_type,64),character_id:text(value.character_id,120),attempt_id:text(value.attempt_id,120),frame_index:Number.isInteger(value.frame_index)?value.frame_index:null,issue_type:text(value.issue_type,100),strategy:text(value.strategy,120),score_before:score(value.score_before),score_after:score(value.score_after),success:value.success==null?null:Boolean(value.success),summary:text(value.summary,300)||value.event_type.replaceAll('_',' ')};await appendFile(this.logPath,JSON.stringify(event)+'\n','utf8');this.events.push(event);this.events=this.events.slice(-2000);return structuredClone(event);}
  recent({limit=25,event_type=null,animation_type=null,character_id=null,attempt_id=null}={}){limit=Math.max(1,Math.min(100,Number(limit)||25));return this.events.filter(event=>(!event_type||event.event_type===event_type)&&(!animation_type||event.animation_type===animation_type)&&(!character_id||event.character_id===character_id)&&(!attempt_id||event.attempt_id===attempt_id)).slice(-limit).reverse().map(event=>structuredClone(event));}
  summary(query={}){const recent=this.recent({...query,limit:query.limit||40}),repairs=recent.filter(event=>['repair_succeeded','repair_failed'].includes(event.event_type)),successes=repairs.filter(event=>event.success).length,groups=new Map();for(const event of repairs){const key=`${event.animation_type||'Animation'}:${event.issue_type||'other'}:${event.strategy||'default'}`,group=groups.get(key)||{animation_type:event.animation_type,issue_type:event.issue_type,strategy:event.strategy,attempts:0,successes:0};group.attempts++;if(event.success)group.successes++;groups.set(key,group);}const lessons=[...groups.values()].map(group=>({...group,success_rate:group.attempts?Math.round(group.successes*100/group.attempts):0,lesson:`${group.strategy||'Default repair'} succeeded ${group.successes} of ${group.attempts} times for ${group.issue_type||'animation issues'}.`})).sort((a,b)=>b.success_rate-a.success_rate||b.attempts-a.attempts);return {recent,repair_outcomes:{attempts:repairs.length,successes,success_rate:repairs.length?Math.round(successes*100/repairs.length):null},lessons};}
  animationLessons(query={}){return this.experienceService?.causal_lessons(query,{limit:Math.max(1,Math.min(100,Number(query.limit)||50))})||[];}
}
