import {createServer} from 'node:http';
import {timingSafeEqual} from 'node:crypto';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import {Service} from './service.mjs';
import {createMcpSession} from './mcp.mjs';

const port=Number(process.env.PORT||8080),host=process.env.HOST||'0.0.0.0',root=path.resolve(process.env.SPRITED_DATA_ROOT||'./data/chatgpt-app'),token=process.env.SPRITED_REMOTE_TOKEN||'';if(!Number.isInteger(port)||port<1||port>65535)throw Error('PORT must be a valid TCP port');if(!token)throw Error('SPRITED_REMOTE_TOKEN is required for the remote runtime');
await mkdir(root,{recursive:true});const service=await new Service(root).init(),sessions=new Map();
const authorized=req=>{const actual=Buffer.from(req.headers.authorization||''),expected=Buffer.from(`Bearer ${token}`);return actual.length===expected.length&&timingSafeEqual(actual,expected);};
const server=createServer(async(req,res)=>{res.setHeader('cache-control','no-store');res.setHeader('access-control-allow-origin','https://chatgpt.com');res.setHeader('access-control-allow-headers','authorization,content-type,mcp-session-id');res.setHeader('access-control-expose-headers','mcp-session-id');if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}const pathname=new URL(req.url,'http://sprited.invalid').pathname;if(pathname==='/health'&&req.method==='GET'){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({status:'ok',service:'sprited-chatgpt-app',version:'0.13.0-dev'}));}if(pathname!=='/mcp'){res.writeHead(404);return res.end();}if(!authorized(req)){res.writeHead(401,{'content-type':'application/json'});return res.end(JSON.stringify({error:'Authentication required'}));}
  try{const sessionId=String(req.headers['mcp-session-id']||'');if(req.method==='DELETE'){const session=sessions.get(sessionId);if(session){await session.close();sessions.delete(sessionId);}res.writeHead(204);return res.end();}if(req.method!=='POST'){res.writeHead(405);return res.end();}let size=0,chunks=[];for await(const chunk of req){size+=chunk.length;if(size>13*1024*1024)throw Error('Request too large');chunks.push(chunk);}const message=JSON.parse(Buffer.concat(chunks).toString()||'{}');let session=sessions.get(sessionId),created=false;if(message.method==='initialize'&&!session){session=createMcpSession(service,{plugin:true});sessions.set(session.sessionId,session);created=true;}if(!session)throw Error('Initialize an MCP session first');const reply=await session.handle(message);if(created)res.setHeader('mcp-session-id',session.sessionId);res.setHeader('content-type','application/json');if(!reply){res.writeHead(202);return res.end();}res.end(JSON.stringify(reply));}catch(error){res.writeHead(400,{'content-type':'application/json'});res.end(JSON.stringify({jsonrpc:'2.0',id:null,error:{code:-32603,message:error.message||'Request failed'}}));}});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,host,resolve);});console.log(`SPRITED ChatGPT App MCP listening on port ${port}`);
const stop=async()=>{server.close();for(const session of sessions.values())await session.close().catch(()=>{});await service.close();process.exit(0);};process.on('SIGTERM',stop);process.on('SIGINT',stop);
