import {readFile,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';

const cleanText=(value,max=1200)=>typeof value==='string'&&value.trim()?value.trim().slice(0,max):null;
const score=value=>Number.isFinite(value)?Math.max(0,Math.min(100,Number(value))):null;
const list=value=>[...new Set((Array.isArray(value)?value:[]).map(item=>cleanText(item,160)).filter(Boolean))];
const load=async(file,fallback)=>{try{return JSON.parse(await readFile(file,'utf8'));}catch(error){if(error.code==='ENOENT')return structuredClone(fallback);throw error;}};
const save=async(file,value)=>{const temp=path.join(path.dirname(file),`${path.basename(file)}.${randomUUID()}.tmp`);await writeFile(temp,JSON.stringify(value),{flag:'wx'});await rename(temp,file);};

export const FAILURE_TAXONOMY=Object.freeze({
  motion:Object.freeze(['no_forward_progression','bad_weight_transfer','broken_contact_pose','broken_passing_pose','broken_up_pose','leg_progression','arm_leg_coordination','pose_duplicate','pose_regression','motion_semantics']),
  continuity:Object.freeze(['visual_jump','center_drift','scale_drift','baseline_drift','silhouette_jump','direction_flip','loop_center_jump','loop_scale_jump','bad_visual_loop']),
  identity:Object.freeze(['character_identity_drift','costume_or_armor_drift','equipment_drift','anatomy']),
  structure:Object.freeze(['invalid_format','frame_count','missing_index','missing_frame_index','duplicate_index','duplicate_frame_index','dimension_mismatch','loop_dimension_mismatch','clipping','other'])
});
const knownIssues=new Set(Object.values(FAILURE_TAXONOMY).flat());
export function classifyFailure(issueType){const issue_type=cleanText(issueType,100)||'other',issue_family=Object.entries(FAILURE_TAXONOMY).find(([,values])=>values.includes(issue_type))?.[0]||'other';return {issue_type,issue_family};}

const words=value=>new Set((cleanText(value)||'').toLowerCase().split(/[^a-z0-9_]+/).filter(token=>token.length>2));
export function compareStrategies(previous={},current={}){
  const before=words(previous.instruction_summary),after=words(current.instruction_summary),added=[...after].filter(item=>!before.has(item)).slice(0,40),removed=[...before].filter(item=>!after.has(item)).slice(0,40),modified=[];
  for(const field of ['repair_action','phase_focus','reference_context'])if(cleanText(previous[field])!==cleanText(current[field]))modified.push({field,before:cleanText(previous[field]),after:cleanText(current[field])});
  return {constraints_added:list(current.constraints_added||added),constraints_removed:list(current.constraints_removed||removed),constraints_modified:Array.isArray(current.constraints_modified)?current.constraints_modified.slice(0,40):modified,phase_focus:{before:cleanText(previous.phase_focus),after:cleanText(current.phase_focus)},reference_context:{before:cleanText(previous.reference_context),after:cleanText(current.reference_context)}};
}

const contextKey=value=>[value.animation_type||'ANY',value.issue_type||'other',value.frame_phase||value.phase||'ANY'].join('|');
const outcomeOf=record=>record.outcome||((record.new_issue_introduced||record.overall_delta<0)?'regressive':record.repair_succeeded?'successful':record.overall_delta>0?'partial':'failed');
function summarize(records){
  const attempts=records.length,successes=records.filter(item=>outcomeOf(item)==='successful').length,partials=records.filter(item=>outcomeOf(item)==='partial').length,failures=records.filter(item=>outcomeOf(item)==='failed').length,regressions=records.filter(item=>outcomeOf(item)==='regressive').length,deltas=records.map(item=>item.overall_delta).filter(Number.isFinite),average_delta=deltas.length?deltas.reduce((sum,value)=>sum+value,0)/deltas.length:0,success_rate=attempts?successes/attempts:0;
  let confidence='experimental';if(successes>=2&&success_rate>=2/3&&average_delta>0)confidence='provisional';if(successes>=3&&attempts>=4&&success_rate>=.75&&average_delta>0&&regressions===0)confidence='trusted';
  const ranking_score=success_rate*100+average_delta-regressions*20-failures*8+partials*2;
  return {attempts,successes,partials,failures,regressions,success_rate,average_delta,ranking_score,confidence};
}

export class ExperienceService {
  constructor({experiencePath,timingPath,now=()=>new Date().toISOString()}){this.experiencePath=experiencePath;this.timingPath=timingPath;this.now=now;this.experiences={version:2,records:[],strategy_stats:[],causal_lessons:[]};this.timings={version:1,operations:{}};}
  async init(){
    const stored=await load(this.experiencePath,{version:2,records:[],strategy_stats:[],causal_lessons:[]});
    if(![1,2].includes(stored.version)||!Array.isArray(stored.records))throw Error('Unsupported operational history format');
    this.experiences={version:2,records:stored.records.map(item=>this.normalizeRecord(item)),strategy_stats:[],causal_lessons:[]};this.rebuildLearningState();
    this.timings=await load(this.timingPath,{version:1,operations:{}});if(this.timings.version!==1||!this.timings.operations)throw Error('Unsupported operational history format');return this;
  }
  normalizeRecord(value,old={}){
    const taxonomy=classifyFailure(value.issue_type||old.issue_type),before={...(old.validator_scores_before||{}),...(value.validator_scores_before||{})},after={...(old.validator_scores_after||{}),...(value.validator_scores_after||{})};
    for(const [legacy,key] of [['technical_score_before','technical'],['semantic_score_before','semantic']])if(score(value[legacy])!==null)before[key]=score(value[legacy]);
    for(const [legacy,key] of [['technical_score_after','technical'],['semantic_score_after','semantic']])if(score(value[legacy])!==null)after[key]=score(value[legacy]);
    for(const key of ['technical','semantic','loop','continuity','identity','overall']){before[key]=score(before[key]);after[key]=score(after[key]);}
    const beforeOverall=before.overall??before.semantic??before.technical,afterOverall=after.overall??after.semantic??after.technical,overall_delta=beforeOverall!==null&&afterOverall!==null?afterOverall-beforeOverall:null;
    const original_issue_persisted=value.original_issue_persisted??old.original_issue_persisted??null,new_issue_introduced=Boolean(value.new_issue_introduced??old.new_issue_introduced),repair_succeeded=value.repair_succeeded==null?Boolean(old.repair_succeeded):Boolean(value.repair_succeeded);
    const outcome=value.outcome||(new_issue_introduced||overall_delta<0?'regressive':repair_succeeded&&!original_issue_persisted?'successful':overall_delta>0?'partial':'failed');
    const attempt_id=cleanText(value.attempt_id||value.experience_id||old.attempt_id||old.experience_id,160)||randomUUID(),frame_phase=cleanText(value.frame_phase||value.phase||old.frame_phase||old.phase,80);
    return {attempt_id,experience_id:attempt_id,parent_attempt_id:cleanText(value.parent_attempt_id??old.parent_attempt_id,160),animation_type:cleanText(value.animation_type||old.animation_type,64),frame_count:Number.isInteger(value.frame_count)?value.frame_count:old.frame_count??null,frame_phase,phase:frame_phase,...taxonomy,character_category:cleanText(value.character_category||old.character_category,80),frame_index:Number.isInteger(value.frame_index)?value.frame_index:old.frame_index??null,strategy_id:cleanText(value.strategy_id||value.repair_action||old.strategy_id||old.repair_action,120)||'regenerate',strategy_version:Number.isInteger(value.strategy_version)?value.strategy_version:old.strategy_version??1,repair_action:cleanText(value.repair_action||old.repair_action,100)||'regenerate',strategy_source:cleanText(value.strategy_source||old.strategy_source,40)||'default',strategy_diff:value.strategy_diff||old.strategy_diff||compareStrategies(value.previous_strategy||{},value.current_strategy||{repair_action:value.repair_action,instruction_summary:value.repair_instruction_summary}),repair_instruction_summary:cleanText(value.repair_instruction_summary??old.repair_instruction_summary),provider:cleanText(value.provider||old.provider,80),issue_types_before:list(value.issue_types_before||old.issue_types_before||[taxonomy.issue_type]),issue_types_after:list(value.issue_types_after||old.issue_types_after),validator_scores_before:before,validator_scores_after:after,technical_score_before:before.technical,semantic_score_before:before.semantic,technical_score_after:after.technical,semantic_score_after:after.semantic,metric_deltas:Object.fromEntries(Object.keys(before).map(key=>[key,before[key]!==null&&after[key]!==null?after[key]-before[key]:null])),overall_delta,repair_succeeded,outcome,original_issue_persisted,new_issue_introduced,new_issue_types:list(value.new_issue_types||old.new_issue_types),created_at:value.created_at||old.created_at||this.now(),updated_at:this.now()};
  }
  rebuildLearningState(){
    const groups=new Map();for(const record of this.experiences.records){const key=`${contextKey(record)}|${record.strategy_id}`,group=groups.get(key)||[];group.push(record);groups.set(key,group);}
    this.experiences.strategy_stats=[...groups.entries()].map(([,records])=>{const latest=records.at(-1),stats=summarize(records);return {context_key:contextKey(latest),animation_type:latest.animation_type,issue_type:latest.issue_type,issue_family:latest.issue_family,frame_phase:latest.frame_phase,strategy_id:latest.strategy_id,repair_action:latest.repair_action,...stats,last_used_at:latest.updated_at};}).sort((a,b)=>b.ranking_score-a.ranking_score||b.attempts-a.attempts);
    this.experiences.causal_lessons=this.experiences.strategy_stats.filter(item=>item.confidence!=='experimental').map(item=>{const records=groups.get(`${item.context_key}|${item.strategy_id}`),latest=[...records].reverse().find(record=>record.repair_instruction_summary)||records.at(-1);return {lesson_id:`${item.context_key}|${item.strategy_id}`,animation_type:item.animation_type,issue_type:item.issue_type,issue_family:item.issue_family,frame_phase:item.frame_phase,strategy_id:item.strategy_id,repair_action:item.repair_action,confidence:item.confidence,evidence_count:item.attempts,success_rate:item.success_rate,average_delta:item.average_delta,prompt_guidance:latest.repair_instruction_summary||`Use ${item.repair_action.replaceAll('_',' ')} while preserving unrelated frame details.`,summary:`${item.confidence} lesson: ${item.repair_action} improved ${item.issue_type}${item.frame_phase?` during ${item.frame_phase}`:''} in ${item.successes}/${item.attempts} comparable attempts.`};});
  }
  async record_experience(value){const id=value.attempt_id||value.experience_id||randomUUID(),index=this.experiences.records.findIndex(item=>item.attempt_id===id),old=index>=0?this.experiences.records[index]:{},record=this.normalizeRecord({...value,attempt_id:id},old);if(index<0)this.experiences.records.push(record);else this.experiences.records[index]=record;this.experiences.records=this.experiences.records.slice(-2000);this.rebuildLearningState();await save(this.experiencePath,this.experiences);return structuredClone(record);}
  query_relevant_experience(query,{limit=50}={}){return this.experiences.records.filter(record=>(!query.animation_type||record.animation_type===query.animation_type)&&(!query.issue_type||record.issue_type===classifyFailure(query.issue_type).issue_type)&&(!query.frame_phase||record.frame_phase===query.frame_phase)).map(record=>{let relevance=0;if(query.animation_type)relevance+=5;if(query.issue_type)relevance+=6;if(query.frame_phase)relevance+=5;if(query.character_category&&record.character_category===query.character_category)relevance+=2;if(query.provider&&record.provider===query.provider)relevance+=1;return {record,relevance};}).sort((a,b)=>b.relevance-a.relevance||b.record.created_at.localeCompare(a.record.created_at)).slice(0,limit).map(item=>({...structuredClone(item.record),relevance:item.relevance}));}
  causal_lessons(query={},options={}){const limit=Math.max(1,Math.min(100,Number(options.limit||query.limit)||50));return this.experiences.causal_lessons.filter(item=>(!query.animation_type||item.animation_type===query.animation_type)&&(!query.issue_type||item.issue_type===classifyFailure(query.issue_type).issue_type)&&(!query.frame_phase||item.frame_phase===query.frame_phase)).sort((a,b)=>(b.confidence==='trusted')-(a.confidence==='trusted')||b.success_rate-a.success_rate||b.evidence_count-a.evidence_count).slice(0,limit).map(item=>structuredClone(item));}
  rank_repair_strategies(query,defaultAction){
    const relevant=this.query_relevant_experience(query,{limit:500}),groups=new Map();for(const record of relevant){const group=groups.get(record.strategy_id)||[];group.push(record);groups.set(record.strategy_id,group);}
    const ranked=[...groups.entries()].map(([strategy_id,records])=>({strategy_id,repair_action:records.at(-1).repair_action,...summarize(records)})).sort((a,b)=>(b.confidence==='trusted')-(a.confidence==='trusted')||(b.confidence!=='experimental')-(a.confidence!=='experimental')||b.ranking_score-a.ranking_score||b.attempts-a.attempts);
    const attempts=ranked.reduce((sum,item)=>sum+item.attempts,0),best=ranked.find(item=>item.confidence!=='experimental'),lesson=best?this.causal_lessons({...query},{limit:20}).find(item=>item.strategy_id===best.strategy_id):null;
    if(!best)return {repair_action:defaultAction,strategy_id:defaultAction,strategy_source:'default',confidence:'experimental',historical_attempts:attempts,historical_success_rate:null,causal_lesson:null,ranked_strategies:ranked};
    return {...best,strategy_source:'experience',historical_attempts:best.attempts,historical_success_rate:best.success_rate,causal_lesson:lesson,ranked_strategies:ranked};
  }
  async record_timing(operation,provider,durationMs){if(!Number.isFinite(durationMs)||durationMs<0)return null;const key=`${provider||'any'}:${operation}`,old=this.timings.operations[key],samples=(old?.samples||0)+1,average_ms=old?Math.round(old.average_ms*.7+durationMs*.3):Math.round(durationMs);const item={operation,provider:provider||null,samples,average_ms,last_ms:Math.round(durationMs),updated_at:this.now()};this.timings.operations[key]=item;await save(this.timingPath,this.timings);return structuredClone(item);}
  average_duration(operation,provider){return this.timings.operations[`${provider||'any'}:${operation}`]?.average_ms??this.timings.operations[`any:${operation}`]?.average_ms??null;}
  async ensure_persisted(){await save(this.experiencePath,this.experiences);const value=await load(this.experiencePath,null);if(!value||value.version!==2||!Array.isArray(value.records)||value.records.length!==this.experiences.records.length||!Array.isArray(value.causal_lessons))throw Error('Experience history could not be verified');return {record_count:value.records.length,lesson_count:value.causal_lessons.length};}
}
