const UNKNOWN=null;
const clamp01=value=>Math.max(0,Math.min(1,Number(value)));
const finite=value=>value==null||value===''?null:Number.isFinite(Number(value))?Number(value):null;
const clone=value=>value==null?value:structuredClone(value);
const freeze=value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child);}return value;};
const byTime=(a,b)=>a.timeline_position-b.timeline_position;
const near=(a,b)=>Math.abs(a-b)<1e-9;

export const VIRTUAL_MOTION_STATE_FIELDS=Object.freeze(['body_center','center_of_mass_progression','body_vertical_position','body_rotation_orientation','facing_direction','weight_distribution','balance_state','pelvis_state','torso_state','head_stabilization','left_arm_trajectory_state','right_arm_trajectory_state','left_leg_trajectory_state','right_leg_trajectory_state','major_limb_relationships','support_contact_state','weapon_tool_trajectory','shield_equipment_trajectory','pose_openness_compression','motion_direction','anticipation_amount','follow_through_amount','recovery_amount']);

export const MOTION_OBSERVATION_FIELDS=Object.freeze([
  'timeline_position','recognized_key_pose_id','body_center','body_vertical_state','body_rotation','weight_direction','balance_state','facing_direction','major_limb_positions','left_right_limb_relationship','contact_support_state','pose_openness_compression','weapon_tool_position','motion_direction','pose_confidence','observation_confidence'
]);

export const TRANSITION_OBSERVATION_FIELDS=Object.freeze([
  'source_frame','target_frame','timeline_interval','expected_timeline_direction','observed_movement_direction','body_displacement','vertical_progression','limb_progression','velocity_progression','acceleration_progression','pose_change_magnitude','continuity_confidence','duplicate_near_duplicate_likelihood','reversal_likelihood','skipped_motion_likelihood','loop_seam_discontinuity','observation_confidence'
]);

function normalizedItem(item,label){
  const timeline_position=finite(item?.timeline_position);
  if(timeline_position===null||timeline_position<0||timeline_position>1)throw Error(`${label} timeline_position must be normalized from 0 to 1`);
  return {...clone(item),timeline_position};
}

function normalizeKeyPoses(keyPoses=[]){
  const poses=keyPoses.map((item,index)=>({...normalizedItem(item,`Key pose ${index}`),id:item.id||`pose-${index}`,name:item.name||item.id||`Pose ${index}`,is_anchor:Boolean(item.is_anchor)})).sort(byTime);
  if(!poses.length)throw Error('ActionMotionSpec requires at least one key pose');
  if(new Set(poses.map(item=>item.id)).size!==poses.length)throw Error('ActionMotionSpec key pose ids must be unique');
  return poses;
}

function defaultSegments(keyPoses,cyclic){
  const segments=[];
  for(let index=0;index<keyPoses.length-1;index++)segments.push({id:`${keyPoses[index].id}->${keyPoses[index+1].id}`,source_motion_state:keyPoses[index].id,target_motion_state:keyPoses[index+1].id,timeline_range:[keyPoses[index].timeline_position,keyPoses[index+1].timeline_position]});
  if(cyclic){const last=keyPoses.at(-1),first=keyPoses[0];segments.push({id:`${last.id}->${first.id}`,source_motion_state:last.id,target_motion_state:first.id,timeline_range:[last.timeline_position,1],wrap_target_position:first.timeline_position});}
  return segments;
}

function normalizeSegments(segments,keyPoses,cyclic){
  const poseIds=new Set(keyPoses.map(item=>item.id));
  return (segments?.length?segments:defaultSegments(keyPoses,cyclic)).map((segment,index)=>{
    const range=segment.timeline_range||[];
    if(range.length!==2||finite(range[0])===null||finite(range[1])===null||range[0]<0||range[1]>1||range[1]<range[0])throw Error(`Motion segment ${index} requires a normalized timeline_range`);
    if(!poseIds.has(segment.source_motion_state)||!poseIds.has(segment.target_motion_state))throw Error(`Motion segment ${index} references an unknown key pose`);
    return {id:segment.id||`segment-${index}`,source_motion_state:segment.source_motion_state,target_motion_state:segment.target_motion_state,timeline_range:[Number(range[0]),Number(range[1])],expected_trajectory:clone(segment.expected_trajectory)||null,expected_body_progression:clone(segment.expected_body_progression)||null,expected_limb_progression:clone(segment.expected_limb_progression)||null,velocity_intent:segment.velocity_intent??null,acceleration_intent:segment.acceleration_intent??null,easing:segment.easing??null,action_specific_mechanics:clone(segment.action_specific_mechanics)||null,important_event_boundaries:[...(segment.important_event_boundaries||[])],repair_range:[...(segment.repair_range||range)]};
  });
}

/** Create the action definition that exists independently of rendered frame count. */
export function createActionMotionSpec(input={}){
  if(typeof input.action_type!=='string'||!input.action_type.trim())throw Error('ActionMotionSpec requires action_type');
  const cyclic=Boolean(input.cyclic),key_poses=normalizeKeyPoses(input.key_poses),motion_events=(input.motion_events||[]).map((item,index)=>({...normalizedItem(item,`Motion event ${index}`),id:item.id||`event-${index}`,name:item.name||item.id||`Event ${index}`})).sort(byTime),motion_segments=normalizeSegments(input.motion_segments,key_poses,cyclic),anchors=key_poses.filter(item=>item.is_anchor).map(item=>item.id);
  return freeze({version:1,schema:'action-motion-spec/v1',action_type:input.action_type,cyclic,start_state:clone(input.start_state)??key_poses[0].id,end_state:clone(input.end_state)??(cyclic?key_poses[0].id:key_poses.at(-1).id),normalized_timeline:{start:0,end:1},key_poses,motion_events,motion_segments,body_mechanics:clone(input.body_mechanics)||null,direction_of_movement:input.direction_of_movement??null,acceleration_deceleration_intent:clone(input.acceleration_deceleration_intent)||null,weight_shift:clone(input.weight_shift)||null,center_of_mass_progression:clone(input.center_of_mass_progression)||null,major_limb_trajectories:clone(input.major_limb_trajectories)||null,anticipation:clone(input.anticipation)||null,action_impact_point:clone(input.action_impact_point)||null,follow_through:clone(input.follow_through)||null,recovery:clone(input.recovery)||null,loop_seam:cyclic?(clone(input.loop_seam)||{source:key_poses.at(-1).id,target:key_poses[0].id}):null,important_anchor_pose_ids:[...(input.important_anchor_pose_ids||anchors)],required_key_pose_ids:[...(input.required_key_pose_ids||key_poses.map(item=>item.id))],required_key_pose_order:[...(input.required_key_pose_order||key_poses.map(item=>item.id))],required_event_order:[...(input.required_event_order||[])],allow_direction_reversal:Boolean(input.allow_direction_reversal),expected_temporal_progression:clone(input.expected_temporal_progression)||null,sampling_intent:clone(input.sampling_intent)||{mode:'uniform'},action_specific_mechanics:clone(input.action_specific_mechanics)||null});
}

export function createMotionTimeline(actionMotionSpec){
  const spec=actionMotionSpec;
  if(spec?.schema!=='action-motion-spec/v1')throw Error('MotionTimeline requires an ActionMotionSpec');
  return freeze({version:1,schema:'motion-timeline/v1',action_type:spec.action_type,cyclic:spec.cyclic,start:0,end:1,key_poses:spec.key_poses.map(({id,name,timeline_position,is_anchor})=>({id,name,timeline_position,is_anchor})),events:spec.motion_events.map(({id,name,timeline_position,...details})=>({id,name,timeline_position,details})),segments:spec.motion_segments.map(segment=>({id:segment.id,timeline_range:[...segment.timeline_range],source_motion_state:segment.source_motion_state,target_motion_state:segment.target_motion_state}))});
}

function easingName(segment){const declared=String(segment?.easing||segment?.acceleration_intent||segment?.velocity_intent||'constant').toLowerCase();if(declared.includes('ease-in-out'))return 'ease-in-out';if(declared.includes('decelerat')||declared.includes('ease-out')||declared.includes('slowing'))return 'ease-out';if(declared.includes('accelerat')||declared.includes('ease-in'))return 'ease-in';return 'constant';}
function easedProgress(progress,easing){if(easing==='ease-in')return progress*progress;if(easing==='ease-out')return 1-(1-progress)*(1-progress);if(easing==='ease-in-out')return progress<.5?2*progress*progress:1-2*(1-progress)*(1-progress);return progress;}
function speedAt(progress,easing){if(easing==='ease-in')return 2*progress;if(easing==='ease-out')return 2*(1-progress);if(easing==='ease-in-out')return progress<.5?4*progress:4*(1-progress);return 1;}
function accelerationAt(progress,easing){if(easing==='ease-in')return 2;if(easing==='ease-out')return -2;if(easing==='ease-in-out')return progress<.5?4:-4;return 0;}
function interpolateValue(source,target,progress){if(source==null)return clone(target);if(target==null)return clone(source);if(Number.isFinite(source)&&Number.isFinite(target))return source+(target-source)*progress;if(Array.isArray(source)&&Array.isArray(target)&&source.length===target.length&&source.every(Number.isFinite)&&target.every(Number.isFinite))return source.map((value,index)=>value+(target[index]-value)*progress);if(typeof source==='object'&&typeof target==='object'&&!Array.isArray(source)&&!Array.isArray(target)){const result={};for(const key of new Set([...Object.keys(source),...Object.keys(target)]))result[key]=interpolateValue(source[key],target[key],progress);return result;}return clone(progress<.5?source:target);}
function poseState(pose){return pose?.virtual_motion_state||pose?.expected_state||{};}
function segmentAt(spec,position){return spec.motion_segments.find((segment,index)=>position>=segment.timeline_range[0]&&(position<segment.timeline_range[1]||(!spec.cyclic&&index===spec.motion_segments.length-1&&near(position,segment.timeline_range[1]))))||spec.motion_segments.at(-1)||null;}
function surrounding(items,position,cyclic){const ordered=[...items].sort(byTime),before=[...ordered].reverse().find(item=>item.timeline_position<=position)||(cyclic?ordered.at(-1):ordered[0]),after=ordered.find(item=>item.timeline_position>=position)||(cyclic?ordered[0]:ordered.at(-1));return {before,after};}

/** Resolve the intended non-rendered action state at arbitrary normalized time t. */
export function sampleVirtualMotion(virtualMotion,t){
  if(virtualMotion?.schema!=='virtual-motion/v1')throw Error('sampleVirtualMotion requires VirtualMotion');const numeric=finite(t);if(numeric===null||numeric<0||numeric>1)throw Error('VirtualMotion time must be normalized from 0 to 1');
  const spec=virtualMotion.action_motion_spec,loopWrapped=spec.cyclic&&near(numeric,1),position=loopWrapped?0:numeric,segment=segmentAt(spec,position),source=spec.key_poses.find(item=>item.id===segment?.source_motion_state)||spec.key_poses[0],target=spec.key_poses.find(item=>item.id===segment?.target_motion_state)||source,range=segment?.timeline_range||[position,position],duration=Math.max(0,range[1]-range[0]),segmentProgress=duration?clamp01((position-range[0])/duration):0,easing=easingName(segment),trajectoryProgress=easedProgress(segmentProgress,easing),exact=spec.key_poses.find(item=>near(item.timeline_position,position))||null,interpolated=exact?clone(poseState(exact)):interpolateValue(poseState(source),poseState(target),trajectoryProgress),neighbors=surrounding(spec.key_poses,position,spec.cyclic),activeEvents=spec.motion_events.filter(event=>near(event.timeline_position,position)),state={version:1,schema:'virtual-motion-state/v1',timeline_position:numeric,resolved_timeline_position:position,loop_wrapped:loopWrapped,current_phase:exact?.name||`${source?.name||source?.id} → ${target?.name||target?.id}`,key_pose_id:exact?.id||null,motion_segment_id:segment?.id||null,segment_progress:segmentProgress,trajectory_progress:trajectoryProgress,easing,expected_velocity:{intent:segment?.velocity_intent||'constant',normalized_speed:speedAt(segmentProgress,easing)},expected_acceleration:{intent:segment?.acceleration_intent||'constant',normalized_acceleration:accelerationAt(segmentProgress,easing)},active_motion_events:activeEvents.map(event=>({id:event.id,name:event.name,type:event.type||null,timeline_position:event.timeline_position})),surrounding_key_poses:{previous:{id:neighbors.before?.id,name:neighbors.before?.name,timeline_position:neighbors.before?.timeline_position},next:{id:neighbors.after?.id,name:neighbors.after?.name,timeline_position:neighbors.after?.timeline_position}},source_motion_state:source?.id||null,target_motion_state:target?.id||null,action_specific_mechanics:clone(exact?.action_specific_mechanics||segment?.action_specific_mechanics)||null};
  for(const field of VIRTUAL_MOTION_STATE_FIELDS)state[field]=interpolated?.[field]??null;state.motion_direction ??= segment?.expected_trajectory?.motion_direction??spec.direction_of_movement??null;const defined=VIRTUAL_MOTION_STATE_FIELDS.filter(field=>state[field]!=null).length;state.definition_completeness=defined/VIRTUAL_MOTION_STATE_FIELDS.length;state.confidence=state.definition_completeness;return freeze(state);
}

/** Construct the complete intended action before any frame count is chosen. */
export function buildVirtualMotion(actionMotionSpec,{timeline=createMotionTimeline(actionMotionSpec)}={}){if(actionMotionSpec?.schema!=='action-motion-spec/v1'||timeline?.schema!=='motion-timeline/v1')throw Error('VirtualMotion requires ActionMotionSpec and MotionTimeline');const base={version:1,schema:'virtual-motion/v1',action_type:actionMotionSpec.action_type,cyclic:actionMotionSpec.cyclic,normalized_timeline:{start:0,end:1},action_motion_spec:actionMotionSpec,motion_timeline:timeline,key_poses:actionMotionSpec.key_poses,motion_events:actionMotionSpec.motion_events,motion_segments:actionMotionSpec.motion_segments};const checkpoints=[...new Set([0,1,...actionMotionSpec.key_poses.map(item=>item.timeline_position),...actionMotionSpec.motion_events.map(item=>item.timeline_position)])].sort((a,b)=>a-b);base.preview_states=checkpoints.map(t=>sampleVirtualMotion(base,t));base.definition_completeness=base.preview_states.reduce((sum,state)=>sum+state.definition_completeness,0)/Math.max(1,base.preview_states.length);return freeze(base);}

export function validateVirtualMotion(virtualMotion,{samplingPlan=null}={}){
  const issues=[],spec=virtualMotion?.action_motion_spec,timeline=virtualMotion?.motion_timeline;if(virtualMotion?.schema!=='virtual-motion/v1'||!spec||!timeline)return {status:'FAIL',passed:false,issues:[{type:'invalid_virtual_motion'}]};
  const poses=spec.key_poses||[],segments=spec.motion_segments||[],poseIds=new Set(poses.map(item=>item.id));for(let index=1;index<poses.length;index++)if(poses[index].timeline_position<=poses[index-1].timeline_position)issues.push({type:'invalid_timeline_order',key_pose_id:poses[index].id});if(!near(poses[0]?.timeline_position,0))issues.push({type:'missing_start_key_pose'});if(!spec.cyclic&&!near(poses.at(-1)?.timeline_position,1))issues.push({type:'missing_end_key_pose'});for(const id of spec.required_key_pose_ids||[])if(!poseIds.has(id))issues.push({type:'missing_required_key_pose',key_pose_id:id});for(const id of spec.important_anchor_pose_ids||[])if(!poseIds.has(id)||!poses.find(item=>item.id===id)?.is_anchor)issues.push({type:'missing_required_anchor',key_pose_id:id});
  for(let index=0;index<segments.length;index++){const segment=segments[index],next=segments[index+1];if(segment.timeline_range[1]<segment.timeline_range[0])issues.push({type:'impossible_segment_order',motion_segment_id:segment.id});if(index===0&&!near(segment.timeline_range[0],0)||index===segments.length-1&&!near(segment.timeline_range[1],1))issues.push({type:'segment_timeline_gap',motion_segment_id:segment.id});if(next&&(!near(segment.timeline_range[1],next.timeline_range[0])||segment.target_motion_state!==next.source_motion_state))issues.push({type:'segment_discontinuity',motion_segment_id:segment.id,next_motion_segment_id:next.id});if(next&&!spec.allow_direction_reversal){const a=segment.expected_trajectory?.motion_direction,b=next.expected_trajectory?.motion_direction;if(a&&b&&a!==b)issues.push({type:'unexpected_motion_reversal',motion_segment_id:next.id});}}
  for(let index=0;index<(spec.required_key_pose_order||[]).length;index++)if(poses[index]?.id!==spec.required_key_pose_order[index])issues.push({type:'invalid_key_pose_order',expected:spec.required_key_pose_order[index],actual:poses[index]?.id||null});const eventKeys=new Set();for(const event of spec.motion_events||[]){const key=`${event.type||event.name}@${event.timeline_position}`;if(eventKeys.has(event.id)||eventKeys.has(key))issues.push({type:'duplicated_important_event',event_id:event.id});eventKeys.add(event.id);eventKeys.add(key);}const eventById=new Map(spec.motion_events.map(item=>[item.id,item]));for(let index=1;index<(spec.required_event_order||[]).length;index++){const before=eventById.get(spec.required_event_order[index-1]),after=eventById.get(spec.required_event_order[index]);if(!before||!after||before.timeline_position>=after.timeline_position)issues.push({type:'invalid_event_order',before:spec.required_event_order[index-1],after:spec.required_event_order[index]});}
  if(spec.cyclic){const first=poses[0],last=poses.at(-1),finalSegment=segments.at(-1);if(spec.loop_seam?.source!==last?.id||spec.loop_seam?.target!==first?.id||finalSegment?.target_motion_state!==first?.id||spec.start_state!==spec.end_state)issues.push({type:'broken_cyclic_seam'});}else if(spec.start_state!==poses[0]?.id||spec.end_state!==poses.at(-1)?.id)issues.push({type:'incompatible_start_end_state'});
  if(samplingPlan&&['anchor-preserving','event-aware'].includes(samplingPlan.mode))for(const id of spec.important_anchor_pose_ids||[]){const pose=poses.find(item=>item.id===id);if(pose&&!samplingPlan.samples.some(sample=>near(sample.timeline_position,pose.timeline_position)))issues.push({type:'sampling_skips_required_anchor',key_pose_id:id});}
  return {version:1,schema:'virtual-motion-validation/v1',status:issues.length?'FAIL':'PASS',passed:issues.length===0,issues};
}

function uniformPositions(count,cyclic){if(count<1)throw Error('SamplingPlan frame_count must be positive');if(count===1)return [0];return Array.from({length:count},(_,index)=>index/(cyclic?count:count-1));}
function anchorPreservingPositions(spec,count,{eventAware=false}={}){
  const anchors=spec.key_poses.filter(item=>spec.important_anchor_pose_ids.includes(item.id)).map(item=>item.timeline_position);
  const positions=[...new Set(anchors)].slice(0,count),priority=eventAware?[...spec.motion_events.map(item=>item.timeline_position),...spec.key_poses.map(item=>item.timeline_position)]:[],candidates=[...priority,...uniformPositions(count,spec.cyclic),...spec.key_poses.map(item=>item.timeline_position)];
  for(const position of candidates){if(positions.length>=count)break;if(!positions.some(value=>near(value,position)))positions.push(position);}
  for(let divisor=count+1;positions.length<count;divisor++)for(let index=1;index<divisor&&positions.length<count;index++){const position=index/divisor;if((!spec.cyclic||position<1)&&!positions.some(value=>near(value,position)))positions.push(position);}
  return positions.sort((a,b)=>a-b).slice(0,count);
}

/** Convert Motion(t) into deterministic rendered sample points. */
export function createSamplingPlan(actionOrVirtualMotion,{frameCount,mode=(actionOrVirtualMotion?.action_motion_spec||actionOrVirtualMotion)?.sampling_intent?.mode||'uniform'}={}){
  const count=Number(frameCount);if(!Number.isInteger(count)||count<1)throw Error('SamplingPlan frame_count must be a positive integer');
  if(!['uniform','anchor-preserving','event-aware'].includes(mode))throw Error(`Unsupported deterministic sampling mode: ${mode}`);
  const virtualMotion=actionOrVirtualMotion?.schema==='virtual-motion/v1'?actionOrVirtualMotion:buildVirtualMotion(actionOrVirtualMotion),preSamplingValidation=validateVirtualMotion(virtualMotion);if(!preSamplingValidation.passed)throw Error(`INVALID_VIRTUAL_MOTION: ${preSamplingValidation.issues.map(item=>item.type).join(', ')}`);const spec=virtualMotion.action_motion_spec,positions=mode==='uniform'?uniformPositions(count,spec.cyclic):anchorPreservingPositions(spec,count,{eventAware:mode==='event-aware'}),anchors=spec.key_poses.filter(item=>spec.important_anchor_pose_ids.includes(item.id));
  const samples=positions.map((timeline_position,frame_index)=>{const virtual_motion_state=sampleVirtualMotion(virtualMotion,timeline_position),keyPose=spec.key_poses.find(item=>near(item.timeline_position,timeline_position))||null,segment=segmentAt(spec,timeline_position),surroundingKeyPoses=surrounding(spec.key_poses,timeline_position,spec.cyclic),surroundingAnchors=surrounding(anchors,timeline_position,spec.cyclic);return {frame_index,timeline_position,key_pose_id:keyPose?.id||null,key_pose_name:keyPose?.name||null,is_key_pose:Boolean(keyPose),is_anchor:Boolean(keyPose&&spec.important_anchor_pose_ids.includes(keyPose.id)),motion_segment_id:segment?.id||null,source_motion_state:segment?.source_motion_state||null,target_motion_state:segment?.target_motion_state||null,motion_state_before:surroundingKeyPoses.before?.id||null,motion_state_after:surroundingKeyPoses.after?.id||null,previous_anchor_id:surroundingAnchors.before?.id||null,next_anchor_id:surroundingAnchors.after?.id||null,expected_progression:segment?{trajectory:segment.expected_trajectory,body:segment.expected_body_progression,limbs:segment.expected_limb_progression,velocity_intent:segment.velocity_intent,acceleration_intent:segment.acceleration_intent,easing:easingName(segment)}:null,virtual_motion_state};});
  const anchorPriority=spec.sampling_intent?.anchor_priority||[],anchorIndexes=samples.filter(item=>item.is_anchor).sort((a,b)=>{const ai=anchorPriority.indexOf(a.key_pose_id),bi=anchorPriority.indexOf(b.key_pose_id);return (ai<0?Number.MAX_SAFE_INTEGER:ai)-(bi<0?Number.MAX_SAFE_INTEGER:bi)||a.frame_index-b.frame_index;}).map(item=>item.frame_index),keyIndexes=samples.filter(item=>item.is_key_pose&&!item.is_anchor).map(item=>item.frame_index),otherIndexes=samples.filter(item=>!item.is_key_pose).map(item=>item.frame_index);
  return freeze({version:2,schema:'sampling-plan/v2',action_type:spec.action_type,cyclic:spec.cyclic,mode,frame_count:count,virtual_motion_schema:virtualMotion.schema,samples,generation_order:[...anchorIndexes,...keyIndexes,...otherIndexes]});
}

export function createMotionObservation(input={}){
  const observation={version:1,schema:'motion-observation/v1',frame_index:Number.isInteger(input.frame_index)?input.frame_index:null};
  for(const field of MOTION_OBSERVATION_FIELDS)observation[field]=input[field]===undefined?UNKNOWN:clone(input[field]);
  observation.unknown_fields=MOTION_OBSERVATION_FIELDS.filter(field=>observation[field]===null);
  return observation;
}

function point(value){if(Array.isArray(value)&&value.length>=2&&value.every(Number.isFinite))return {x:value[0],y:value[1]};if(value&&Number.isFinite(value.x)&&Number.isFinite(value.y))return {x:value.x,y:value.y};return null;}
function derivePair(source,target,sample,nextSample,loopSeam){
  const a=point(source.body_center),b=point(target.body_center),body_displacement=a&&b?{x:b.x-a.x,y:b.y-a.y,magnitude:Math.hypot(b.x-a.x,b.y-a.y)}:null,sameLimbs=source.major_limb_positions!=null&&target.major_limb_positions!=null&&JSON.stringify(source.major_limb_positions)===JSON.stringify(target.major_limb_positions),duplicateLikelihood=body_displacement&&body_displacement.magnitude<.001&&sameLimbs?1:null,confidence=Math.min(finite(source.observation_confidence)??0,finite(target.observation_confidence)??0);
  return createTransitionObservation({source_frame:sample.frame_index,target_frame:nextSample.frame_index,timeline_interval:[sample.timeline_position,loopSeam?1:nextSample.timeline_position],expected_timeline_direction:'forward',observed_movement_direction:target.motion_direction,body_displacement,vertical_progression:source.body_vertical_state!=null&&target.body_vertical_state!=null?{from:source.body_vertical_state,to:target.body_vertical_state}:null,limb_progression:source.major_limb_positions!=null&&target.major_limb_positions!=null?{from:source.major_limb_positions,to:target.major_limb_positions}:null,pose_change_magnitude:null,continuity_confidence:null,duplicate_near_duplicate_likelihood:duplicateLikelihood,reversal_likelihood:null,skipped_motion_likelihood:null,loop_seam_discontinuity:null,observation_confidence:confidence});
}

export function createTransitionObservation(input={}){const result={version:1,schema:'transition-observation/v1'};for(const field of TRANSITION_OBSERVATION_FIELDS)result[field]=input[field]===undefined?UNKNOWN:clone(input[field]);result.detected_issues=[...(input.detected_issues||[])];result.responsible_frame=Number.isInteger(input.responsible_frame)?input.responsible_frame:null;result.unknown_fields=TRANSITION_OBSERVATION_FIELDS.filter(field=>result[field]===null);return result;}

export function deriveTransitionObservations(samplingPlan,motionObservations={}){
  const samples=samplingPlan?.samples||[],lookup=new Map(Object.entries(motionObservations||{}).map(([key,value])=>[Number(key),value?.schema==='motion-observation/v1'?value:createMotionObservation({frame_index:Number(key),...value})])),count=samples.length-(samplingPlan?.cyclic?0:1),result=[];
  for(let index=0;index<count;index++){const sample=samples[index],nextSample=samples[(index+1)%samples.length],source=lookup.get(sample.frame_index),target=lookup.get(nextSample.frame_index);result.push(source&&target?derivePair(source,target,sample,nextSample,index===samples.length-1&&samplingPlan.cyclic):createTransitionObservation({source_frame:sample.frame_index,target_frame:nextSample.frame_index,timeline_interval:[sample.timeline_position,index===samples.length-1&&samplingPlan.cyclic?1:nextSample.timeline_position],expected_timeline_direction:'forward',observation_confidence:null}));}
  return result;
}

export function compareIntendedAndObservedMotion(actionMotionSpec,samplingPlan,motionObservations={},transitionObservations=[],{confidenceThreshold=.6}={}){
  const transitions=transitionObservations.length?transitionObservations:deriveTransitionObservations(samplingPlan,motionObservations),segments=new Map(actionMotionSpec.motion_segments.map(item=>[item.id,item]));
  return transitions.map((observation,index)=>{const sample=samplingPlan.samples[index],next=samplingPlan.samples[(index+1)%samplingPlan.samples.length],segment=segments.get(sample.motion_segment_id)||null,confidence=finite(observation.observation_confidence),issues=[...(observation.detected_issues||[])],expectedInterval=[sample.timeline_position,index===transitions.length-1&&samplingPlan.cyclic?1:next.timeline_position],actualInterval=observation.timeline_interval;if(confidence===null||confidence<confidenceThreshold)issues.push('insufficient_observation');if(observation.expected_timeline_direction&&observation.expected_timeline_direction!=='forward'||actualInterval&&(actualInterval[0]!==expectedInterval[0]||actualInterval[1]!==expectedInterval[1]))issues.push('chronological_progression');if((finite(observation.reversal_likelihood)??0)>=.6||segment?.expected_trajectory?.motion_direction&&observation.observed_movement_direction&&segment.expected_trajectory.motion_direction!==observation.observed_movement_direction)issues.push('reversed_motion');if((finite(observation.skipped_motion_likelihood)??0)>=.6)issues.push('skipped_motion');if((finite(observation.duplicate_near_duplicate_likelihood)??0)>=.6)issues.push('repeated_pose');if((finite(observation.continuity_confidence)??1)<.5)issues.push('motion_discontinuity');if(segment?.acceleration_intent&&observation.acceleration_progression?.matches_expected===false)issues.push('acceleration_mismatch');if(segment?.velocity_intent&&observation.velocity_progression?.matches_expected===false)issues.push('velocity_mismatch');if(index===transitions.length-1&&samplingPlan.cyclic&&(finite(observation.loop_seam_discontinuity)??0)>=.6)issues.push('loop_pop');const unique=[...new Set(issues)],insufficient=unique.includes('insufficient_observation'),status=insufficient?'INSUFFICIENT_OBSERVATION':unique.length?'FAIL':'PASS';return {source_frame:observation.source_frame??sample.frame_index,target_frame:observation.target_frame??next.frame_index,timeline_interval:observation.timeline_interval||expectedInterval,motion_segment_id:sample.motion_segment_id,expected_transition:segment,observed_transition:observation,status,detected_issues:unique,confidence:confidence??0,loop_relevance:index===transitions.length-1&&samplingPlan.cyclic,responsible_frames:status==='FAIL'?[observation.responsible_frame??observation.target_frame??next.frame_index]:[]};});
}
