const WALK_PHASES=['left contact','left down','left passing','left up','right contact','right down','right passing','right up'];
const pairIndex=(index,total)=>total>=4&&total%2===0?((index+total/2)%total):null;
const sideFor=phase=>/^left\b/i.test(phase)?'left':/^right\b/i.test(phase)?'right':null;

export function buildPosePlan(run,{frameCount=run.options?.output_frames||run.recipe_snapshot?.default_output_frame_count||run.frame_records?.length||0}={}){
  const phases=run.recipe_snapshot?.motion_template?.phases?.length?run.recipe_snapshot.motion_template.phases:frameCount===8?WALK_PHASES:Array.from({length:frameCount},(_,index)=>`phase ${index+1}`);
  const frames=Array.from({length:frameCount},(_,frame_index)=>{const animation_phase=phases[Math.min(phases.length-1,Math.floor(frame_index*phases.length/Math.max(1,frameCount)))],side=sideFor(animation_phase),paired_frame_index=pairIndex(frame_index,frameCount),paired_phase=paired_frame_index===null?null:phases[Math.min(phases.length-1,Math.floor(paired_frame_index*phases.length/Math.max(1,frameCount)))];return {frame_index,animation_phase,anatomical_lead_leg:side,anatomical_trailing_leg:side?side==='left'?'right':'left':null,planted_foot:animation_phase?.includes('contact')?side:null,lifted_foot:animation_phase?.includes('contact')?(side==='left'?'right':'left'):null,pelvis_progression:animation_phase?.includes('up')?'raised':animation_phase?.includes('down')?'lowered':'forward',torso_direction:'match reference direction',arm_counter_swing:side?`counter-swing opposite ${side} lead leg`:null,expected_silhouette_characteristics:side?`allow ${side} lead stride silhouette change while preserving identity`:'preserve coherent motion silhouette',neighbor_frame_indexes:[frame_index>0?frame_index-1:null,frame_index<frameCount-1?frame_index+1:null].filter(Number.isInteger),paired_frame_index,paired_phase,paired_relation:paired_frame_index===null?null:`same phase, opposite lead/trailing legs`,required_neighbor_relation:'continuous progression without duplicate pose',required_paired_relation:paired_frame_index===null?null:'contralateral counterpart; do not preserve identical silhouette'};});
  return {version:1,animation_type:run.animation_type,frame_count:frameCount,frames,paired_frames:frames.filter(frame=>frame.paired_frame_index!==null).map(frame=>({frame_index:frame.frame_index,paired_frame_index:frame.paired_frame_index,phase:frame.animation_phase,paired_phase:frame.paired_phase,lead_trail_swap_required:true})),priority_order:['animation phase correctness','anatomical left/right correctness','lead/trail leg relationship','pelvis / weight progression','character identity','equipment consistency','silhouette consistency']};
}

export function poseFor(plan,index){return plan?.frames?.find(frame=>frame.frame_index===index)||null;}

export function createRepairPlanDetails({pose,issue,description,pairedFrame=null,neighbors=[],strategy='frame_local'}={}){
  const gait=pose?.anatomical_lead_leg&&['contact','down','passing','up'].some(name=>pose.animation_phase?.includes(name));
  const mustChange=gait&&issue&&['leg_progression','bad_weight_transfer','broken_contact_pose','broken_passing_pose','no_forward_progression'].includes(issue)?[`correct ${pose.anatomical_lead_leg} lead leg and ${pose.anatomical_trailing_leg} trailing leg`,`match ${pose.animation_phase} pelvis/weight progression`,'allow the expected contralateral silhouette change']:['correct the reported defect'];
  const mustPreserve=['character identity and proportions','armor/clothing, colors and equipment','camera angle, direction, scale and framing'];
  return {target_issue:issue||'other',target_frame:pose?.frame_index??null,target_phase:pose?.animation_phase||null,current_failure:description||issue||'reported validation issue',likely_cause:gait?'paired-frame / contralateral gait relationship':null,must_change:mustChange,must_not_change:mustPreserve,neighbor_frames:neighbors,paired_frame:pairedFrame?{frame_index:pairedFrame.frame_index,phase:pairedFrame.animation_phase,lead_leg:pairedFrame.anatomical_lead_leg,required_relation:pairedFrame.required_paired_relation}:null,strategy_selected:strategy,repair_dimension:gait?'lead/trail leg correction':'focused frame-local correction',expected_measurable_improvement:['target issue score improves','no critical identity/anatomy regression',...(pairedFrame?['lead_trail_swap_correct','paired_phase_match']:[])],rollback_condition:'reject if target issue worsens or BEST_KNOWN_RESULT materially regresses'};
}

export function validatePairedPoseRelation(plan,observed={}){const diagnostics=[];for(const pair of plan?.paired_frames||[]){const left=observed[pair.frame_index],right=observed[pair.paired_frame_index],a=plan.frames[pair.frame_index],b=plan.frames[pair.paired_frame_index];if(!a||!b)continue;const swapped=left?.lead_leg&&right?.lead_leg?left.lead_leg!==right.lead_leg:true;diagnostics.push({frame_index:pair.frame_index,paired_frame_index:pair.paired_frame_index,paired_phase_match:a.animation_phase===b.paired_phase,lead_trail_swap_correct:swapped,stride_amplitude_symmetry:observed.stride_amplitude_symmetry??null,pelvis_progression_symmetry:observed.pelvis_progression_symmetry??null,arm_counter_swing_match:observed.arm_counter_swing_match??null,incorrect_same_side_repetition:!swapped});}return diagnostics;}
