const stageOrder=['preparing','generating','importing','validating','diagnosing','repairing','semantic_reinspection','revalidating','finalizing','persisting_experience','cleaning_temporary_artifacts','completed'];
const messages={preparing:'Preparing animation',generating:'Generating frames',importing:'Importing frames',validating:'Validating animation',diagnosing:'Diagnosing frame issues',repairing:'Repairing frames',semantic_reinspection:'Waiting for semantic reinspection',revalidating:'Re-validating repaired frames',finalizing:'Finalizing result',persisting_experience:'Saving repair experience',cleaning_temporary_artifacts:'Cleaning temporary artifacts',completed:'Animation ready',blocked:'Workflow blocked',failed:'Workflow failed'};

export class ProgressTracker {
  constructor(history,{now=()=>Date.now()}={}){this.history=history;this.now=now;}
  update(previous,{animation_id,stage,status_message,provider,current_repair_attempt=0,max_repair_attempts=3,remaining_operations={},completed_stage_count,total_known_stage_count,user_action_required=false}={}){
    const now=this.now(),started=previous?.started_at||new Date(now).toISOString(),elapsed=Math.max(0,now-Date.parse(started)),priorCompleted=previous?.completed_stage_count||0,computedCompleted=completed_stage_count??Math.max(0,stageOrder.indexOf(stage)),completed=Math.max(priorCompleted,computedCompleted),extra=Object.values(remaining_operations).reduce((sum,value)=>sum+(Number.isFinite(value)?Math.max(0,value):0),0),total=Math.max(total_known_stage_count||0,previous?.total_known_stage_count||0,stageOrder.length-1,completed+extra),terminal=stage==='completed',percent=terminal?100:Math.min(99,Math.max(previous?.progress_percent||0,Math.round(completed/Math.max(1,total)*100)));
    let eta=0,known=false;for(const [operation,count] of Object.entries(remaining_operations)){const average=this.history.average_duration(operation,provider);if(average!=null){eta+=average*Math.max(0,count);known=true;}}
    const paused=Boolean(user_action_required),estimated=paused||!known?null:Math.max(0,Math.round(eta));return {animation_id,current_stage:stage,completed_stage_count:completed,total_known_stage_count:total,progress_percent:percent,elapsed_ms:elapsed,estimated_remaining_ms:estimated,current_repair_attempt,max_repair_attempts,status_message:status_message||messages[stage]||stage,eta_paused:paused,status:paused?'user_action_required':stage,provider:provider||null,remaining_operations:{...remaining_operations},started_at:started,updated_at:new Date(now).toISOString()};
  }
}
